// Seed anglais — le namespace `legal`, et lui seul.
// Assemblé dans `../en.ts`; une clé `legal.*` ne vit qu'ici (`dictionaryChunks.int.test.ts`).

export const enLegal = {
  // ── chantier-0904/FF-060 — fin ──


  // ── /legal — MENTIONS LÉGALES, CGU, CONFIDENTIALITÉ, CGV, PARRAINAGE ────
  //
  // ⚠️ CETTE PAGE ÉTAIT LE DERNIER ÉCRAN PUBLIC HORS DU SEED, et `catalog.ts`
  // écrivait pourquoi: son corps était mille lignes d'anglais EN DUR, donc la
  // déclarer aurait promis une page française autour d'un texte juridique
  // anglais. C'est cette extraction-là qui lève l'obstacle — le texte anglais
  // ci-dessous est celui de la page, repris MOT POUR MOT, ponctuation comprise.
  //
  // ⚠️ LES FAITS D'IDENTITÉ NE SONT PAS ICI. Le nom, la forme, le capital, le
  // RCS, la TVA, l'adresse, le téléphone et l'e-mail viennent tous de
  // `lib/legalEntity.ts` et arrivent en PARAMÈTRES: ce sont les clés de
  // jointure entre le domaine et le registre du commerce, et deux rédactions
  // d'un numéro de TVA divergent. Une adresse postale n'est pas de la langue.
  //
  // ⚠️ LE GRAS A DISPARU DE QUATRE PHRASES, ET C'EST VOULU. Le JSX écrivait
  // `<strong>` au MILIEU d'une phrase (« The <strong>invoices</strong>
  // relating to… »): trois morceaux dont l'ordre est celui de l'anglais, donc
  // irrecollables en français. Là où l'emphase porte une phrase entière ou une
  // amorce (« Renewal: », « Identity data: »), elle est gardée en DEUX clés.
  "legal.seo.title": "Legal notice & Terms",
  "legal.seo.description":
    "Legal notice for {domain}: publisher, registered office, VAT number, hosting, terms of use, privacy policy and terms of sale.",
  "legal.page.title": "Legal notice & terms",
  "legal.page.intro":
    "Who publishes {domain}, how to reach us, and the terms that govern the service.",
  "legal.page.updated": "Last updated: {date}",

  "legal.nav.mentions": "Legal notice",
  "legal.nav.cgu": "Terms of use",
  "legal.nav.privacy": "Privacy",
  "legal.nav.cgv": "Terms of sale",
  "legal.nav.referral": "Referral",

  "legal.mentions.title": "Legal notice",
  "legal.mentions.subtitle":
    "Publisher identity, as required by article 6-III of the French LCEN",
  "legal.mentions.intro":
    "The site {domain} and the Sophia service are published by {name}, {form} with share capital of {capital}, registered with the French Trade and Companies Register (RCS) under number {rcs}, whose registered office is at {office}.",
  "legal.mentions.row_publisher": "Publisher",
  "legal.mentions.row_form": "Legal form",
  "legal.mentions.row_capital": "Share capital",
  "legal.mentions.row_rcs": "RCS number",
  "legal.mentions.row_vat": "Intra-EU VAT number",
  "legal.mentions.row_office": "Registered office",
  "legal.mentions.row_director": "Publication director",
  "legal.mentions.row_contact": "Contact",
  "legal.mentions.row_phone": "Phone",
  // Le nom de la forme sociale reste en français dans les deux packs:
  // `legalEntity.ts` le dit déjà de `legalForm` — « Kept in French: it is a
  // form in French law ». Le traduire inventerait une société qui n'existe pas.
  "legal.mentions.form_value": "Société par actions simplifiée (SAS), France",
  "legal.mentions.hosting_title": "Hosting",
  "legal.mentions.hosting_body":
    "The site is hosted by {name}, {street}, {city}, {region} {postal}, United States.",
  "legal.mentions.ip_title": "Intellectual property",
  "legal.mentions.ip_body":
    "This site as a whole is governed by French and international copyright and intellectual property law. All reproduction rights are reserved, including for downloadable documents and for iconographic and photographic material.",

  "legal.cgu.title": "Terms of use",
  "legal.cgu.subtitle": "Rules for accessing and using the platform",
  "legal.cgu.s1_title": "1. Purpose and acceptance",
  "legal.cgu.s1_p1":
    "These Terms of Use (the \"Terms\") govern access to and use of the \"Sophia\" SaaS platform (the \"Service\"), published by {name} (the \"Publisher\").",
  "legal.cgu.s1_p2":
    "Using the Service implies unreserved acceptance of these Terms. The user acknowledges having read all of the conditions before ticking the \"I accept\" box when signing up.",
  "legal.cgu.s2_title": "2. Description of the Service",
  "legal.cgu.s2_p1":
    "Sophia is an intelligent virtual assistant (AI) for personal development, productivity and life design. The Service allows you in particular to:",
  "legal.cgu.s2_li1":
    "Generate personalised action plans to organise your days and reach your goals.",
  "legal.cgu.s2_li2":
    "Interact with a conversational AI for motivational support and habit tracking.",
  "legal.cgu.s2_li3": "Access tools for structuring identity and tracking progress.",
  "legal.cgu.ai_notice_label": "AI notice:",
  "legal.cgu.ai_notice_body":
    "The advice and content generated by Sophia are produced by artificial intelligence algorithms. They are provided for information and decision support, and cannot replace human professional judgement or constitute certified legal, medical or financial advice.",
  "legal.cgu.s3_title": "3. Access to the Service",
  "legal.cgu.s3_p1":
    "The Service is available 24/7, except in cases of force majeure or maintenance. The Publisher reserves the right to suspend, interrupt or limit access to all or part of the Service for technical or security reasons, without this giving rise to compensation.",
  "legal.cgu.s4_title": "4. User account",
  "legal.cgu.s4_p1":
    "Registration is required to access the features. The User is solely responsible for keeping their credentials confidential. Any action taken from their account is deemed to have been taken by them. If credentials are lost or stolen, the User must inform the Publisher without delay.",
  "legal.cgu.s5_title": "5. Intellectual property",
  "legal.cgu.s5_service_label": "Service content:",
  "legal.cgu.s5_service_body":
    "All elements of the Service (structure, design, code, algorithms, the \"Sophia\" trade marks) are the exclusive property of {name}. Any reproduction is prohibited without authorisation.",
  "legal.cgu.s5_user_label": "User content:",
  "legal.cgu.s5_user_body":
    "The data, text and information provided by the User remain their property. The User grants the Publisher a right to use this content solely for operating and improving the Service (including training AI models, in anonymised form).",
  "legal.cgu.s6_title": "6. Liability",
  "legal.cgu.s6_p1":
    "The Publisher provides the Service under a best-efforts obligation. It cannot be held liable for:",
  "legal.cgu.s6_li1": "Indirect damages (loss of revenue, loss of opportunity, and so on).",
  "legal.cgu.s6_li2": "AI advice being unsuited to the User's specific situation.",
  "legal.cgu.s6_li3": "Problems related to the User's own internet connection.",
  "legal.cgu.s6_li4":
    "The consequences of a failure, security incident or hack occurring on third-party providers' infrastructure (hosting, AI model providers, messaging), where no proven fault of the Publisher in selecting or configuring those services is established.",

  "legal.privacy.title": "Privacy policy",
  "legal.privacy.subtitle": "Protection of your personal data (GDPR)",
  "legal.privacy.s1_title": "1. Data collected",
  "legal.privacy.s1_p1": "When you use Sophia, we collect the following data:",
  "legal.privacy.s1_li1_label": "Identity data:",
  "legal.privacy.s1_li1_body":
    "surname, first name, email, phone number (account identifier).",
  "legal.privacy.s1_li2_label": "Life & goal data:",
  "legal.privacy.s1_li2_body":
    "questionnaire answers, personal goals, generated action plans.",
  "legal.privacy.s1_li3_label": "Conversation data:",
  "legal.privacy.s1_li3_body": "the history of exchanges with the Sophia assistant.",
  "legal.privacy.s1_li4_label": "Technical data:",
  "legal.privacy.s1_li4_body": "sign-in logs, IP address, browser type.",
  "legal.privacy.s2_title": "2. Purposes of processing",
  "legal.privacy.s2_p1": "Your data is processed for the following reasons:",
  "legal.privacy.s2_li1":
    "Providing and personalising the Service (legal basis: performance of the contract).",
  "legal.privacy.s2_li2":
    "Sending notifications and reminders inside the app (legal basis: consent).",
  "legal.privacy.s2_li3":
    "Continuous improvement of the AI algorithms (legal basis: legitimate interest).",
  "legal.privacy.s2_li4": "Handling billing and customer support.",
  "legal.privacy.s3_title": "3. Data sharing",
  "legal.privacy.s3_p1":
    "Your data is strictly confidential. It is passed only to the technical sub-processors we cannot operate without (cloud hosting, AI API provider, message delivery service), who are bound by the same security obligations.",
  "legal.privacy.s3_never_sell": "We never sell your data to advertisers.",
  "legal.privacy.s4_title": "4. Security",
  "legal.privacy.s4_p1":
    "We put in place technical security measures (SSL/TLS encryption, secured databases) and organisational ones to protect your data against unauthorised access, loss or alteration.",
  "legal.privacy.s5_title": "5. Your rights",
  // ⚠️ LE CHEMIN DE MENU RESTE ANGLAIS DANS LES DEUX PACKS, et c'est la règle
  // des citations d'écran de `parity.int.test.ts`: on cite le produit tel
  // qu'il rend, jamais réécrit. `/account` n'est PAS dans `PAGE_NAMESPACES`,
  // donc cet écran est anglais pour tout le monde; traduire le chemin
  // enverrait une lectrice française chercher un menu qui n'existe nulle part.
  // Le jour où `/account` est déclarée, ces deux citations bougent avec elle.
  "legal.privacy.s5_p1":
    "Under the GDPR you have rights of access, rectification, erasure, restriction and portability over your data. You can exercise the erasure and portability rights directly in the app, without contacting us: menu \"Account → Options → My data\" (export your data) and \"Delete my account\".",
  "legal.privacy.s6_title": "6. Data retention and deletion",
  "legal.privacy.s6_self_label": "Self-service account deletion:",
  "legal.privacy.s6_self_body":
    "you can delete your account at any time from the app. Deletion happens in two stages:",
  "legal.privacy.s6_li1_label": "Immediately:",
  "legal.privacy.s6_li1_body":
    "your access is disabled, Sophia stops writing to you and your subscription is cancelled with no further charge.",
  "legal.privacy.s6_li2_label": "Within 7 days:",
  "legal.privacy.s6_li2_body":
    "all of your data (profile, plans, conversations, memories) is permanently and irreversibly deleted from our databases. During that period you can cancel the deletion by signing in again.",
  "legal.privacy.s6_kept_title": "Data kept after deletion:",
  "legal.privacy.s6_kept_li1":
    "The invoices relating to your payments, kept under the statutory accounting retention obligation (article L.123-22 of the French Commercial Code).",
  "legal.privacy.s6_kept_li2":
    "A minimal anonymised record of the deletion (cryptographic hashes of the email and phone number, and the deletion date), kept as proof of compliance. It cannot be used to identify you.",
  "legal.privacy.s6_kept_li3":
    "Technical usage measurements (volumes and compute costs), anonymised at deletion time: they are no longer attached to any person.",
  "legal.privacy.s6_backups_label": "Technical backups:",
  "legal.privacy.s6_backups_body":
    "backup copies of our databases may remain temporarily after deletion. They expire automatically on their rotation cycle and are never used to restore deleted data, except in a major technical incident affecting the whole service.",
  "legal.privacy.s6_export_label": "Exporting your data:",
  "legal.privacy.s6_export_body":
    "you can download a copy of your data (profile, plans, conversations, memories) as JSON at any time from the Account menu. For security, re-authentication is required, a notification is sent to you for every request, and exports are limited to one per 24 hours.",
  "legal.privacy.rights_label": "Exercising your rights.",
  // Sans point final: l'adresse est un LIEN, rendu après cette phrase, et le
  // point le suit dans le JSX. Les deux langues finissent sur l'adresse.
  "legal.privacy.rights_body": "For any request about your data, contact us at",

  "legal.cgv.title": "Terms of sale",
  "legal.cgv.subtitle": "Subscriptions, payments and withdrawal",
  "legal.cgv.s1_title": "1. Plans and prices",
  "legal.cgv.s1_p1":
    "Services are offered as subscriptions (monthly or annual) or as one-off purchases. Prices are shown in Euros (€) including all taxes on the \"Pricing\" page. {name} reserves the right to change its prices at any time, but the Service is billed at the prices in force when the order is confirmed.",
  "legal.cgv.s2_title": "2. Payment",
  "legal.cgv.s2_p1":
    "Payment is made by card through our secure payment provider (Stripe). Payment is due immediately on ordering. If payment fails, access to the Service is suspended immediately.",
  "legal.cgv.s3_title": "3. Renewal and cancellation",
  "legal.cgv.s3_renewal_label": "Renewal:",
  "legal.cgv.s3_renewal_body":
    "Subscriptions renew automatically for a period identical to the one originally taken out, unless cancelled by the User.",
  "legal.cgv.s3_cancel_label": "Cancellation:",
  "legal.cgv.s3_cancel_body":
    "The User can cancel their subscription at any time from the \"My Account\" area. Cancellation takes effect at the end of the current subscription period. No pro-rata refund is made for a period already started.",
  "legal.cgv.s4_title": "4. No right of withdrawal",
  "legal.cgv.s4_notice":
    "Under article L.221-28 of the French Consumer Code, the right of withdrawal cannot be exercised for contracts supplying digital content not provided on a physical medium (SaaS) whose performance has begun after the consumer's express prior agreement and express waiver of their right of withdrawal.",
  "legal.cgv.s4_p1":
    "By subscribing to the Service and accessing the digital features immediately, the User expressly waives their right of withdrawal.",
  "legal.cgv.s5_title": "5. Governing law",
  "legal.cgv.s5_p1":
    "These Terms of Sale are governed by French law. In the event of a dispute, jurisdiction is granted to the competent courts in the district of {name}'s registered office, notwithstanding multiple defendants or third-party proceedings.",

  "legal.referral.title": "Referral programme",
  "legal.referral.subtitle": "Programme conditions",
  "legal.referral.s1_title": "1. How it works",
  "legal.referral.s1_p1":
    "Every User has a personal referral code, shareable as a link or a code. When someone (the \"Referee\") creates a Sophia account with that code, their free trial is extended to 30 days (instead of 14). The code must be entered at sign-up: it cannot be added later to an existing account.",
  "legal.referral.s2_title": "2. Referrer reward",
  // Trois clés pour un paragraphe: le gras porte la CONDITION de la
  // récompense, et elle tombe en fin de phrase dans les deux langues.
  "legal.referral.s2_lead":
    "The Referrer receives one (1) free month of subscription, matching the monthly price of their current plan, as a credit deducted from their next invoices. This reward is credited",
  "legal.referral.s2_condition":
    "only when the Referee pays a first invoice for an amount strictly greater than zero",
  "legal.referral.s2_no_entitlement":
    "The Referee merely signing up, the trial period, or a €0 invoice give no entitlement to a reward.",
  "legal.referral.s2_held":
    "If the Referrer is not yet subscribed when their Referee converts, the reward is held and applied automatically to their first invoices as soon as they take out a subscription.",
  "legal.referral.s3_title": "3. Cap",
  "legal.referral.s3_p1":
    "Free months are capped at twelve (12) months per rolling twelve (12) month period per Referrer. Beyond that cap, referrals are still counted but no longer give entitlement to a reward.",
  "legal.referral.s4_title": "4. Anti-fraud reservation",
  "legal.referral.s4_notice":
    "Self-referral (same person, same phone number, or multiple accounts) is prohibited. The Referee must be a new user who does not already have a Sophia account. {name} reserves the right to refuse, suspend or cancel any reward obtained in breach of these conditions or by any fraudulent or abusive means, and to suspend the accounts involved.",
  "legal.referral.s5_title": "5. Nature of the reward",
  "legal.referral.s5_p1":
    "Free months have no monetary value: they are not refundable, transferable or convertible into cash. {name} may change or end the referral programme at any time; rewards already earned remain due.",
} as const
