import { assertEquals } from "jsr:@std/assert@1";

import {
  buildLevelAutoGeneratedEventContext,
  buildLevelAutoGeneratedMessage,
  buildLevelReviewFinalReminderEventContext,
  buildLevelReviewFinalReminderMessage,
  buildLevelReviewReminderEventContext,
  getLevelEndDateYmd,
  getLevelReviewUnlockDateYmd,
  isLevelAutoGeneratedEventContext,
  isLevelReviewReminderEventContext,
} from "./level_review_checkins.ts";
import type { CurrentLevelRuntime, PlanContentV3 } from "./v2-types.ts";

Deno.test("level review window opens two days before the level end", () => {
  const plan = {
    metadata: {
      schedule_anchor: {
        anchor_week_end: "2026-05-10",
      },
    },
  } as Pick<PlanContentV3, "metadata">;
  const currentLevel = {
    duration_weeks: 3,
  } as Pick<CurrentLevelRuntime, "duration_weeks">;

  assertEquals(getLevelEndDateYmd({ plan, currentLevel }), "2026-05-24");
  assertEquals(
    getLevelReviewUnlockDateYmd({ plan, currentLevel }),
    "2026-05-22",
  );
});

Deno.test("level review event contexts are namespaced by plan and phase", () => {
  const reminder = buildLevelReviewReminderEventContext({
    planId: "plan-1",
    phaseId: "phase-2",
  });
  const auto = buildLevelAutoGeneratedEventContext({
    planId: "plan-1",
    phaseId: "phase-2",
  });

  assertEquals(reminder, "level_review_reminder:plan-1:phase-2");
  assertEquals(auto, "level_auto_generated:plan-1:phase-2");
  assertEquals(isLevelReviewReminderEventContext(reminder), true);
  assertEquals(isLevelAutoGeneratedEventContext(auto), true);
});

Deno.test("final reminder context shares the reminder prefix for cancellation and routing", () => {
  const finalContext = buildLevelReviewFinalReminderEventContext({
    planId: "plan-1",
    phaseId: "phase-2",
  });

  assertEquals(finalContext, "level_review_reminder:plan-1:phase-2:final");
  // Routed like a reminder by process-checkins…
  assertEquals(isLevelReviewReminderEventContext(finalContext), true);
  // …and matched by complete-level-v1's LIKE "level_review_reminder:plan:phase%".
  assertEquals(
    finalContext.startsWith("level_review_reminder:plan-1:phase-2"),
    true,
  );
});

Deno.test("final reminder message warns about tonight's auto-generation", () => {
  const message = buildLevelReviewFinalReminderMessage({
    levelTitle: "Niveau test",
    dashboardUrl: "https://app.example.com/dashboard?tab=plan",
  });

  assertEquals(message.includes('"Niveau test"'), true);
  assertEquals(message.includes("ce soir"), true);
  assertEquals(message.includes("https://app.example.com/dashboard?tab=plan"), true);
});

Deno.test("auto generated message summarizes completed and next level", () => {
  const message = buildLevelAutoGeneratedMessage({
    completedLevelTitle: "Niveau A",
    nextLevelTitle: "Niveau B",
    nextLevelDurationWeeks: 3,
    dashboardUrl: "https://app.example.com/dashboard?tab=plan",
  });

  assertEquals(message.includes('"Niveau A"'), true);
  assertEquals(message.includes('"Niveau B" (3 semaines)'), true);

  const fallback = buildLevelAutoGeneratedMessage({
    dashboardUrl: "https://app.example.com/dashboard?tab=plan",
  });
  assertEquals(fallback.includes("garder le rythme"), true);
});

