import type {
  CurrentLevelRuntime,
  PlanContentV3,
} from "./v2-types.ts";

export const LEVEL_REVIEW_REMINDER_EVENT_CONTEXT_PREFIX =
  "level_review_reminder";
export const LEVEL_AUTO_GENERATED_EVENT_CONTEXT_PREFIX =
  "level_auto_generated";
export const LEVEL_REVIEW_ORIGIN = "level_review";

export const LEVEL_REVIEW_REMINDER_LOCAL_TIME = "10:30";
export const LEVEL_AUTO_GENERATED_LOCAL_TIME = "07:15";

function cleanText(value: unknown): string {
  return String(value ?? "").replace(/\s+/g, " ").trim();
}

function parseYmdParts(ymd: string): [number, number, number] | null {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(ymd);
  if (!match) return null;
  return [Number(match[1]), Number(match[2]), Number(match[3])];
}

function dateFromYmdUtc(ymd: string): Date | null {
  const parts = parseYmdParts(ymd);
  if (!parts) return null;
  const [year, month, day] = parts;
  return new Date(Date.UTC(year, month - 1, day, 12, 0, 0));
}

function formatYmdUtc(date: Date): string {
  return date.toISOString().slice(0, 10);
}

export function addDaysYmd(ymd: string, days: number): string | null {
  const date = dateFromYmdUtc(ymd);
  if (!date) return null;
  date.setUTCDate(date.getUTCDate() + days);
  return formatYmdUtc(date);
}

function getScheduleAnchor(plan: Pick<PlanContentV3, "metadata">) {
  const metadata = plan.metadata;
  if (!metadata || typeof metadata !== "object" || Array.isArray(metadata)) {
    return null;
  }
  const anchor = (metadata as Record<string, unknown>).schedule_anchor;
  if (!anchor || typeof anchor !== "object" || Array.isArray(anchor)) {
    return null;
  }
  return anchor as Record<string, unknown>;
}

export function getLevelEndDateYmd(args: {
  plan: Pick<PlanContentV3, "metadata">;
  currentLevel: Pick<CurrentLevelRuntime, "duration_weeks">;
}): string | null {
  const anchor = getScheduleAnchor(args.plan);
  const anchorWeekEnd = cleanText(anchor?.anchor_week_end);
  if (!anchorWeekEnd) return null;
  const durationWeeks = Math.max(1, Math.floor(args.currentLevel.duration_weeks ?? 1));
  return addDaysYmd(anchorWeekEnd, (durationWeeks - 1) * 7);
}

export function getLevelReviewUnlockDateYmd(args: {
  plan: Pick<PlanContentV3, "metadata">;
  currentLevel: Pick<CurrentLevelRuntime, "duration_weeks">;
  unlockDaysBeforeEnd?: number;
}): string | null {
  const endDate = getLevelEndDateYmd(args);
  if (!endDate) return null;
  return addDaysYmd(endDate, -(args.unlockDaysBeforeEnd ?? 2));
}

export function buildLevelReviewReminderEventContext(args: {
  planId: string;
  phaseId: string;
}): string {
  return `${LEVEL_REVIEW_REMINDER_EVENT_CONTEXT_PREFIX}:${args.planId}:${args.phaseId}`;
}

export function buildLevelAutoGeneratedEventContext(args: {
  planId: string;
  phaseId: string;
}): string {
  return `${LEVEL_AUTO_GENERATED_EVENT_CONTEXT_PREFIX}:${args.planId}:${args.phaseId}`;
}

export function isLevelReviewReminderEventContext(value: unknown): boolean {
  return cleanText(value).startsWith(`${LEVEL_REVIEW_REMINDER_EVENT_CONTEXT_PREFIX}:`);
}

export function isLevelAutoGeneratedEventContext(value: unknown): boolean {
  return cleanText(value).startsWith(`${LEVEL_AUTO_GENERATED_EVENT_CONTEXT_PREFIX}:`);
}

export function levelReviewDashboardUrl(siteUrlRaw: unknown): string {
  const siteUrl = cleanText(siteUrlRaw) || "https://app.sophia.app";
  return `${siteUrl.replace(/\/+$/, "")}/dashboard?tab=plan`;
}

export function buildLevelReviewReminderMessage(args: {
  levelTitle: string;
  dashboardUrl: string;
}): string {
  const title = cleanText(args.levelTitle);
  return [
    title
      ? `Ton prochain niveau est pret a etre valide apres "${title}".`
      : "Ton prochain niveau est pret a etre valide.",
    "Prends 2 minutes pour repondre au bilan: Sophia ajustera la suite a partir de ca.",
    args.dashboardUrl,
  ].join("\n\n");
}

export function buildLevelAutoGeneratedMessage(args: {
  nextLevelTitle?: string | null;
  dashboardUrl: string;
}): string {
  const title = cleanText(args.nextLevelTitle);
  return [
    title
      ? `Comme tu n'as pas eu le temps de valider la suite, j'ai prepare ton prochain niveau: "${title}".`
      : "Comme tu n'as pas eu le temps de valider la suite, j'ai prepare ton prochain niveau pour garder le rythme.",
    "Tu peux l'ajuster si quelque chose ne colle pas.",
    args.dashboardUrl,
  ].join("\n\n");
}

