import { assertEquals } from "jsr:@std/assert@1";

import {
  buildLevelAutoGeneratedEventContext,
  buildLevelReviewReminderEventContext,
  getLevelEndDateYmd,
  getLevelReviewUnlockDateYmd,
  isLevelAutoGeneratedEventContext,
  isLevelReviewReminderEventContext,
} from "./level_review_checkins.ts";
import type { CurrentLevelRuntime, PlanContentV3 } from "./v2-types.ts";

Deno.test("level review window opens two days before the level end", () => {
  const plan = {
    metadata: {
      schedule_anchor: {
        anchor_week_end: "2026-05-10",
      },
    },
  } as Pick<PlanContentV3, "metadata">;
  const currentLevel = {
    duration_weeks: 3,
  } as Pick<CurrentLevelRuntime, "duration_weeks">;

  assertEquals(getLevelEndDateYmd({ plan, currentLevel }), "2026-05-24");
  assertEquals(
    getLevelReviewUnlockDateYmd({ plan, currentLevel }),
    "2026-05-22",
  );
});

Deno.test("level review event contexts are namespaced by plan and phase", () => {
  const reminder = buildLevelReviewReminderEventContext({
    planId: "plan-1",
    phaseId: "phase-2",
  });
  const auto = buildLevelAutoGeneratedEventContext({
    planId: "plan-1",
    phaseId: "phase-2",
  });

  assertEquals(reminder, "level_review_reminder:plan-1:phase-2");
  assertEquals(auto, "level_auto_generated:plan-1:phase-2");
  assertEquals(isLevelReviewReminderEventContext(reminder), true);
  assertEquals(isLevelAutoGeneratedEventContext(auto), true);
});

