/// <reference path="../tsserver-shims.d.ts" />
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2.87.3";

import { ensureInternalRequest } from "../_shared/internal-auth.ts";
import { logEdgeFunctionError } from "../_shared/error-log.ts";
import { getRequestId, jsonResponse } from "../_shared/http.ts";
import { computeScheduledForFromLocal } from "../_shared/scheduled_checkins.ts";
import { getUserTimeContext } from "../_shared/user_time_context.ts";
import type {
  CurrentLevelRuntime,
  PlanContentV3,
  UserPlanV2Row,
} from "../_shared/v2-types.ts";
import {
  buildLevelAutoGeneratedEventContext,
  buildLevelAutoGeneratedMessage,
  buildLevelReviewFinalReminderEventContext,
  buildLevelReviewFinalReminderMessage,
  buildLevelReviewReminderEventContext,
  buildLevelReviewReminderMessage,
  getLevelEndDateYmd,
  getLevelReviewUnlockDateYmd,
  LEVEL_AUTO_GENERATED_LOCAL_TIME,
  LEVEL_AUTO_GENERATION_MIN_LOCAL_HOUR,
  LEVEL_REVIEW_FINAL_REMINDER_LOCAL_TIME,
  LEVEL_REVIEW_ORIGIN,
  LEVEL_REVIEW_REMINDER_LOCAL_TIME,
  levelReviewDashboardUrl,
} from "../_shared/level_review_checkins.ts";
import { completeLevelV1 } from "../complete-level-v1/index.ts";

const DEFAULT_LIMIT = 200;
const PENDING_CHECKIN_STATUSES = ["pending", "retrying", "awaiting_user"];

type ActivePlanRow = Pick<
  UserPlanV2Row,
  "id" | "user_id" | "cycle_id" | "transformation_id" | "content" | "status"
>;

function cleanText(value: unknown, fallback = ""): string {
  const text = String(value ?? "").trim();
  return text || fallback;
}

function clampNumber(raw: unknown, fallback: number, min: number, max: number) {
  const n = Number(raw ?? fallback);
  if (!Number.isFinite(n)) return fallback;
  return Math.max(min, Math.min(max, Math.floor(n)));
}

function isWhatsappSchedulingTierEligible(accessTierRaw: unknown): boolean {
  const tier = cleanText(accessTierRaw).toLowerCase();
  return tier === "trial" || tier === "alliance" || tier === "architecte";
}

function getSiteUrl(): string {
  // Prefer APP_BASE_URL (the canonical frontend URL, always set per-project via
  // the Stripe functions) so links never silently fall back to prod on staging.
  return cleanText(
    Deno.env.get("APP_BASE_URL") ?? Deno.env.get("SITE_URL") ??
      Deno.env.get("PUBLIC_SITE_URL"),
    "https://app.sophia.app",
  );
}

function adminClient() {
  return createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    { auth: { persistSession: false, autoRefreshToken: false } },
  );
}

function parsePlanContent(value: unknown): PlanContentV3 | null {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  const content = value as Record<string, unknown>;
  if (content.version !== 3 || !Array.isArray(content.phases)) return null;
  return content as unknown as PlanContentV3;
}

function currentPhaseFor(
  plan: PlanContentV3,
  currentLevel: CurrentLevelRuntime,
) {
  return plan.phases.find((phase) =>
    phase.phase_id === currentLevel.phase_id ||
    phase.phase_order === currentLevel.level_order
  ) ?? null;
}

const LEVEL_REVIEW_IN_FLIGHT_GRACE_MS = 30 * 60 * 1000;

async function hasCompletedOrInFlightLevelTransition(params: {
  admin: ReturnType<typeof createClient>;
  planId: string;
  phaseId: string;
  now: Date;
}): Promise<boolean> {
  // The generation event is the LAST write of completeLevelV1 in every branch
  // (AI generation, keep-runtime, final level): its presence means the
  // transition completed. A review row alone means a previous run crashed
  // mid-transition (e.g. edge timeout during the LLM call) and must NOT be
  // treated as handled — the catch-up window below resumes it, and
  // completeLevelV1 reuses the orphan review instead of duplicating it. A very
  // recent review (< 30 min) is treated as in-flight to avoid racing a run
  // still in progress.
  const [review, event] = await Promise.all([
    params.admin
      .from("user_plan_level_reviews")
      .select("id,created_at")
      .eq("plan_id", params.planId)
      .eq("phase_id", params.phaseId)
      .order("created_at", { ascending: false })
      .limit(1),
    params.admin
      .from("user_plan_level_generation_events")
      .select("id")
      .eq("plan_id", params.planId)
      .eq("from_phase_id", params.phaseId)
      .limit(1),
  ]);
  if (review.error) throw review.error;
  if (event.error) throw event.error;
  if ((event.data ?? []).length > 0) return true;

  const latestReview = (review.data ?? [])[0] as
    | { created_at?: string | null }
    | undefined;
  if (!latestReview) return false;
  const reviewAgeMs = params.now.getTime() -
    new Date(String(latestReview.created_at ?? "")).getTime();
  return Number.isFinite(reviewAgeMs) &&
    reviewAgeMs < LEVEL_REVIEW_IN_FLIGHT_GRACE_MS;
}

async function cancelPendingReminderCheckins(params: {
  admin: ReturnType<typeof createClient>;
  userId: string;
  eventContext: string;
  nowIso: string;
}) {
  // LIKE prefix so the ":final" Sunday-morning reminder is cancelled too.
  const { error } = await params.admin
    .from("scheduled_checkins")
    .update({ status: "cancelled", processed_at: params.nowIso } as any)
    .eq("user_id", params.userId)
    .like("event_context", `${params.eventContext}%`)
    .in("status", PENDING_CHECKIN_STATUSES);
  if (error) throw error;
}

// Send-once guard: any row for this exact event context (pending, sent,
// failed, cancelled) means the reminder was already scheduled once and must
// never be re-created — the hourly cron would otherwise resend it forever.
async function hasAnyReminderCheckin(params: {
  admin: ReturnType<typeof createClient>;
  userId: string;
  eventContext: string;
}): Promise<boolean> {
  const { data, error } = await params.admin
    .from("scheduled_checkins")
    .select("id")
    .eq("user_id", params.userId)
    .eq("event_context", params.eventContext)
    .limit(1);
  if (error) throw error;
  return (data ?? []).length > 0;
}

async function loadProfile(params: {
  admin: ReturnType<typeof createClient>;
  userId: string;
}) {
  const { data, error } = await params.admin
    .from("profiles")
    .select(
      "id,timezone,whatsapp_opted_in,whatsapp_coaching_paused_until,access_tier",
    )
    .eq("id", params.userId)
    .maybeSingle();
  if (error) throw error;
  return data as Record<string, unknown> | null;
}

async function scheduleLevelReviewReminder(params: {
  admin: ReturnType<typeof createClient>;
  userId: string;
  planId: string;
  phaseId: string;
  levelTitle: string;
  timezone: string;
  now: Date;
  nowIso: string;
  dashboardUrl: string;
  final: boolean;
}) {
  // Deterministic local-time slot: combined with the send-once guard this
  // keeps each reminder kind to a single delivery per level.
  const scheduledFor = computeScheduledForFromLocal({
    timezone: params.timezone,
    dayOffset: 0,
    localTimeHHMM: params.final
      ? LEVEL_REVIEW_FINAL_REMINDER_LOCAL_TIME
      : LEVEL_REVIEW_REMINDER_LOCAL_TIME,
    now: params.now,
  });
  const eventContext = params.final
    ? buildLevelReviewFinalReminderEventContext({
      planId: params.planId,
      phaseId: params.phaseId,
    })
    : buildLevelReviewReminderEventContext({
      planId: params.planId,
      phaseId: params.phaseId,
    });
  const draftMessage = params.final
    ? buildLevelReviewFinalReminderMessage({
      levelTitle: params.levelTitle,
      dashboardUrl: params.dashboardUrl,
    })
    : buildLevelReviewReminderMessage({
      levelTitle: params.levelTitle,
      dashboardUrl: params.dashboardUrl,
    });
  const { error } = await params.admin
    .from("scheduled_checkins")
    .upsert(
      {
        user_id: params.userId,
        origin: LEVEL_REVIEW_ORIGIN,
        event_context: eventContext,
        draft_message: draftMessage,
        message_mode: "static",
        message_payload: {
          source: "trigger_level_review_transitions_v1",
          version: 1,
          checkin_kind: params.final
            ? "level_review_final_reminder"
            : "level_review_reminder",
          plan_id: params.planId,
          phase_id: params.phaseId,
          dashboard_url: params.dashboardUrl,
          timezone: params.timezone,
          generated_at: params.nowIso,
        },
        scheduled_for: scheduledFor,
        status: "pending",
      } as any,
      {
        onConflict: "user_id,event_context,scheduled_for",
        ignoreDuplicates: true,
      },
    );
  if (error) throw error;
}

async function scheduleAutoGeneratedNotice(params: {
  admin: ReturnType<typeof createClient>;
  userId: string;
  planId: string;
  phaseId: string;
  completedLevelTitle: string | null;
  nextLevelTitle: string | null;
  nextLevelDurationWeeks: number | null;
  timezone: string;
  now: Date;
  nowIso: string;
  localHour: number;
  dashboardUrl: string;
}) {
  // Sunday-evening auto-generation notifies right away; if the catch-up path
  // fires at night, defer the message to the next morning instead.
  const daytime = params.localHour >= 7 && params.localHour <= 21;
  const scheduledFor = daytime
    ? params.now.toISOString()
    : computeScheduledForFromLocal({
      timezone: params.timezone,
      dayOffset: params.localHour > 21 ? 1 : 0,
      localTimeHHMM: LEVEL_AUTO_GENERATED_LOCAL_TIME,
      now: params.now,
    });
  const eventContext = buildLevelAutoGeneratedEventContext({
    planId: params.planId,
    phaseId: params.phaseId,
  });
  const draftMessage = buildLevelAutoGeneratedMessage({
    completedLevelTitle: params.completedLevelTitle,
    nextLevelTitle: params.nextLevelTitle,
    nextLevelDurationWeeks: params.nextLevelDurationWeeks,
    dashboardUrl: params.dashboardUrl,
  });
  const { error } = await params.admin
    .from("scheduled_checkins")
    .upsert(
      {
        user_id: params.userId,
        origin: LEVEL_REVIEW_ORIGIN,
        event_context: eventContext,
        draft_message: draftMessage,
        message_mode: "static",
        message_payload: {
          source: "trigger_level_review_transitions_v1",
          version: 1,
          checkin_kind: "level_auto_generated_notice",
          source_plan_id: params.planId,
          source_phase_id: params.phaseId,
          dashboard_url: params.dashboardUrl,
          timezone: params.timezone,
          generated_at: params.nowIso,
        },
        scheduled_for: scheduledFor,
        status: "pending",
      } as any,
      {
        onConflict: "user_id,event_context,scheduled_for",
        ignoreDuplicates: true,
      },
    );
  if (error) throw error;
}

Deno.serve(async (req) => {
  const requestId = getRequestId(req);
  try {
    const guard = ensureInternalRequest(req);
    if (guard) return guard;

    const body = await req.json().catch(() => ({} as Record<string, unknown>));
    const userIdFilter = cleanText(body.user_id);
    const dryRun = Boolean(body.dry_run);
    const limit = clampNumber(body.limit, DEFAULT_LIMIT, 1, 1000);
    const now = body.now_iso ? new Date(cleanText(body.now_iso)) : new Date();
    const nowIso = Number.isFinite(now.getTime())
      ? now.toISOString()
      : new Date().toISOString();
    const effectiveNow = new Date(nowIso);

    const admin = adminClient();
    let plansQuery = admin
      .from("user_plans_v2")
      .select("id,user_id,cycle_id,transformation_id,content,status")
      .eq("status", "active")
      .order("updated_at", { ascending: true })
      .limit(limit);
    if (userIdFilter) plansQuery = plansQuery.eq("user_id", userIdFilter);

    const { data: planRows, error: plansError } = await plansQuery;
    if (plansError) throw plansError;

    const dashboardUrl = levelReviewDashboardUrl(getSiteUrl());
    let scanned = 0;
    let skipped = 0;
    let remindersScheduled = 0;
    let autoGenerated = 0;
    const actions: Array<Record<string, unknown>> = [];

    for (const row of (planRows ?? []) as ActivePlanRow[]) {
      scanned++;
      const plan = parsePlanContent(row.content);
      const currentLevel = plan?.current_level_runtime ?? null;
      if (!plan || !currentLevel) {
        skipped++;
        continue;
      }
      const currentPhase = currentPhaseFor(plan, currentLevel);
      if (!currentPhase) {
        skipped++;
        continue;
      }
      const alreadyHandled = await hasCompletedOrInFlightLevelTransition({
        admin,
        planId: row.id,
        phaseId: currentPhase.phase_id,
        now: effectiveNow,
      });
      if (alreadyHandled) {
        skipped++;
        continue;
      }

      const profile = await loadProfile({ admin, userId: row.user_id });
      const timezone = cleanText(profile?.timezone, "Europe/Paris");
      const userTime = await getUserTimeContext({
        supabase: admin as any,
        userId: row.user_id,
        now: effectiveNow,
      });
      const localDate = userTime.user_local_date;
      const unlockDate = getLevelReviewUnlockDateYmd({
        plan,
        currentLevel,
      });
      const endDate = getLevelEndDateYmd({ plan, currentLevel });
      if (!unlockDate || !endDate) {
        skipped++;
        continue;
      }

      const reminderEventContext = buildLevelReviewReminderEventContext({
        planId: row.id,
        phaseId: currentPhase.phase_id,
      });

      const pauseUntilMs = cleanText(profile?.whatsapp_coaching_paused_until)
        ? new Date(cleanText(profile?.whatsapp_coaching_paused_until)).getTime()
        : NaN;
      const whatsappAllowed = Boolean(profile?.whatsapp_opted_in) &&
        isWhatsappSchedulingTierEligible(profile?.access_tier) &&
        !(Number.isFinite(pauseUntilMs) &&
          pauseUntilMs > effectiveNow.getTime());
      const allowsMorning = whatsappAllowed;

      const localHour = userTime.user_local_hour;

      // Auto-generation: past the end date (catch-up), or on the end date
      // (Sunday) once the local evening threshold is reached.
      const autoGenerationDue = localDate > endDate ||
        (localDate === endDate &&
          localHour >= LEVEL_AUTO_GENERATION_MIN_LOCAL_HOUR);

      if (autoGenerationDue) {
        actions.push({
          action: "auto_generate",
          user_id: row.user_id,
          plan_id: row.id,
          phase_id: currentPhase.phase_id,
          local_date: localDate,
          end_date: endDate,
        });
        if (dryRun) continue;

        const result = await completeLevelV1({
          admin: admin as any,
          requestId,
          userId: row.user_id,
          transformationId: row.transformation_id,
          planId: row.id,
          answers: {},
          reviewMode: "auto_timeout",
          autoReason: `auto_timeout_after_level_end:${endDate}`,
        });
        autoGenerated++;
        await cancelPendingReminderCheckins({
          admin,
          userId: row.user_id,
          eventContext: reminderEventContext,
          nowIso,
        });
        if (allowsMorning) {
          await scheduleAutoGeneratedNotice({
            admin,
            userId: row.user_id,
            planId: row.id,
            phaseId: currentPhase.phase_id,
            completedLevelTitle: currentLevel.title ?? null,
            nextLevelTitle: result.nextLevel?.title ?? null,
            nextLevelDurationWeeks: result.nextLevel?.duration_weeks ?? null,
            timezone,
            now: effectiveNow,
            nowIso,
            localHour,
            dashboardUrl,
          });
        }
        continue;
      }

      // End date (Sunday) before the evening threshold: one final reminder in
      // the morning, warning that auto-generation happens tonight.
      if (localDate === endDate) {
        actions.push({
          action: "schedule_final_reminder",
          user_id: row.user_id,
          plan_id: row.id,
          phase_id: currentPhase.phase_id,
          local_date: localDate,
          end_date: endDate,
        });
        if (dryRun || !allowsMorning) continue;
        const finalReminderEventContext =
          buildLevelReviewFinalReminderEventContext({
            planId: row.id,
            phaseId: currentPhase.phase_id,
          });
        if (
          await hasAnyReminderCheckin({
            admin,
            userId: row.user_id,
            eventContext: finalReminderEventContext,
          })
        ) {
          continue;
        }
        await scheduleLevelReviewReminder({
          admin,
          userId: row.user_id,
          planId: row.id,
          phaseId: currentPhase.phase_id,
          levelTitle: currentLevel.title,
          timezone,
          now: effectiveNow,
          nowIso,
          dashboardUrl,
          final: true,
        });
        remindersScheduled++;
        continue;
      }

      // Unlock window (before the end date): the initial reminder, sent once.
      if (localDate >= unlockDate) {
        actions.push({
          action: "schedule_reminder",
          user_id: row.user_id,
          plan_id: row.id,
          phase_id: currentPhase.phase_id,
          local_date: localDate,
          unlock_date: unlockDate,
          end_date: endDate,
        });
        if (dryRun || !allowsMorning) continue;
        if (
          await hasAnyReminderCheckin({
            admin,
            userId: row.user_id,
            eventContext: reminderEventContext,
          })
        ) {
          continue;
        }
        await scheduleLevelReviewReminder({
          admin,
          userId: row.user_id,
          planId: row.id,
          phaseId: currentPhase.phase_id,
          levelTitle: currentLevel.title,
          timezone,
          now: effectiveNow,
          nowIso,
          dashboardUrl,
          final: false,
        });
        remindersScheduled++;
        continue;
      }

      skipped++;
    }

    return jsonResponse(req, {
      ok: true,
      request_id: requestId,
      scanned,
      skipped,
      reminders_scheduled: remindersScheduled,
      auto_generated: autoGenerated,
      dry_run: dryRun,
      actions,
    }, { includeCors: false });
  } catch (error) {
    console.error(
      `[trigger-level-review-transitions-v1] request_id=${requestId}`,
      error,
    );
    await logEdgeFunctionError({
      functionName: "trigger-level-review-transitions-v1",
      requestId,
      error,
      metadata: { source: "edge" },
    });
    return jsonResponse(
      req,
      {
        error: error instanceof Error ? error.message : String(error),
        request_id: requestId,
      },
      { status: 500, includeCors: false },
    );
  }
});
