-- ============================================================================
-- FF-038 · LE RÉFÉRENTIEL DE COMPOSITION
--
-- Fiche: docs/fonctionnalites/composition-des-repas/FF-038-le-referentiel-de-composition.md
-- Design d'origine: scratchpad/DESIGN-UNITES-DE-COMPOSITION.md §2.1
--
-- CE QUE CES DEUX TABLES RENDENT POSSIBLE
-- ---------------------------------------
-- Le produit ne sait pas ce qu'il met dans l'assiette. `DishIngredient` porte
-- une prose libre (`term`, `quantity`) et un booléen calculé (`in_pantry`);
-- aucun chemin du dépôt ne va de « 400 g de cuisses de poulet » à une grandeur
-- quelconque. `food_items` est un catalogue de LIBELLÉS pour l'écran du coach:
-- il porte un `typical_amount`, c'est-à-dire la taille d'une portion, et pas
-- une densité d'aliment. Les deux tables coexistent, partagent leurs slugs là
-- où c'est vrai, et ne se remplacent pas.
--
-- CE QUE CES TABLES NE FONT PAS, ET C'EST LE POINT DE L'ÉTAPE
-- ------------------------------------------------------------
-- Rien. Aucun prompt ne change, aucun parseur ne change, aucune assiette ne
-- change. Cette migration installe un INSTRUMENT DE MESURE, dont la première
-- sortie est un chiffre — la couverture de résolution — qui décide si la suite
-- du chantier (verdicts, boucle de correction) a le droit de démarrer.
--
-- LA SOURCE, ET CE QU'ELLE VAUT
-- -----------------------------
-- ANSES-CIQUAL 2020, XML, licence Etalab, via data.gouv.fr. Le script
-- d'extraction est gardé dans `scratchpad/gen_composition_seed.py` avec son
-- catalogue curé (`ciqual_catalogue.py`): un seed écrit à la main est un seed
-- que personne ne sait régénérer, et celui-ci se rejoue.
--
-- 192 des 208 entrées viennent de Ciqual. Les 16 autres portent
-- `source = 'manual'` parce que Ciqual 2020 ne les contient pas (skyr, cottage
-- cheese, halloumi, huile de coco, graines de courge…). Un référentiel n'est
-- pas moins honnête parce qu'il a deux sources; il l'est quand il ne dit pas
-- laquelle — d'où la colonne.
--
-- L'ÉNERGIE EST PARFOIS CALCULÉE, ET C'EST FIDÈLE
-- -----------------------------------------------
-- Ciqual laisse le champ énergie VIDE pour ~28 % de ses aliments (le miel en
-- fait partie) tout en donnant les macronutriments qui servent à le calculer.
-- L'extraction applique alors l'arithmétique que la constante porte dans son
-- propre nom — « Energie, Règlement UE N° 1169/2011 »: 4 kcal/g pour les
-- protéines et les glucides, 9 pour les lipides, 2 pour les fibres. Ce n'est
-- pas une invention, c'est la définition réglementaire.
--
-- CE QUI N'EST PAS ICI, ET NE LE SERA PAS
-- ---------------------------------------
-- Aucun milligramme de micronutriment. La variance sol/saison/cuisson est de
-- ±30-50 %, et le booléen « source de » est la seule granularité honnête. Les
-- seuils sont ceux du Règlement (CE) 1924/2006 — 15 % de la VNR pour 100 g —
-- appliqués aux teneurs Ciqual. La vitamine D sort entièrement du moteur: elle
-- n'est pas couvrable par l'aliment, c'est un drapeau côté coach.
-- ============================================================================

create table if not exists public.food_composition_refs (
  -- Le slug REPREND ceux de `food_items` là où l'aliment existe des deux côtés
  -- (`chicken_breast`, `salmon`, `oats`…). Pas de FK entre les deux tables:
  -- l'une est un catalogue d'écran qui peut perdre une ligne sans que la
  -- composition d'un aliment cesse d'exister, et l'inverse est vrai aussi.
  slug text primary key,

  -- LE VOCABULAIRE EXISTANT, PAS UN SECOND. Les trente groupes de
  -- `food_groups` portent déjà la FK, le seed, le token-lint et le prompt de
  -- vision. Ce dépôt a payé une duplication de vocabulaire alimentaire; on ne
  -- la refait pas pour une table de composition.
  food_group_ref text not null references public.food_groups(slug),

  label text not null check (length(btrim(label)) between 1 and 80),

  -- ── LA PROVENANCE, SUR LA LIGNE ────────────────────────────────────────
  -- `ciqual_code` et `ciqual_name` disent EXACTEMENT de quelle ligne ANSES la
  -- valeur sort. Ils ne sont pas décoratifs: Ciqual 2020 n'a pas d'énergie
  -- pour beaucoup de formes CRUES (« Brocoli, cru » n'en porte aucune), et
  -- l'extraction retient alors la forme qui en a. Sans le nom retenu, personne
  -- ne peut relire pourquoi le brocoli du référentiel vient d'une ligne
  -- « cuit à l'eau » — et c'est le genre d'écart qu'on veut pouvoir juger.
  source text not null check (source in ('ciqual', 'manual')),
  ciqual_code text,
  ciqual_name text,

  -- ── POUR 100 g CRUS ────────────────────────────────────────────────────
  -- CRUS, et c'est LE piège du domaine: « 100 g de riz » vaut ~350 kcal cru et
  -- ~130 cuit. Le passage cuit→cru se fait par `yield_class`, dans le module,
  -- et il est testé nommément.
  energy_kcal numeric not null check (energy_kcal >= 0),
  -- NULLABLES, et jamais mis à zéro. Ciqual ne donne pas toujours les lipides
  -- d'un céleri. `null` se lit « on ne sait pas »; `0` se lirait « il n'y en a
  -- pas », ce qui est une affirmation que personne n'a faite. Le module
  -- propage l'inconnu (FF-038 R2).
  protein_g numeric check (protein_g >= 0),
  carbs_g numeric check (carbs_g >= 0),
  fat_g numeric check (fat_g >= 0),
  fiber_g numeric check (fiber_g >= 0),

  -- ── LES SENTINELLES, EN BOOLÉENS ───────────────────────────────────────
  -- Présence/absence, jamais des mg. Seuils: 15 % de la VNR pour 100 g
  -- (Règlement CE 1924/2006) — calcium 120 mg, fer 2,1 mg, zinc 1,5 mg,
  -- iode 22,5 µg, B12 0,375 µg, folates 30 µg.
  --
  -- `omega3_marine` n'a pas de VNR utilisable: le seuil est EPA+DHA ≥ 0,3
  -- g/100 g, une constante OPÉRATIONNELLE choisie pour que la sentinelle
  -- veuille dire « poisson gras » (le cabillaud, ~0,2, n'en est pas un). Elle
  -- est avouée comme telle plutôt que présentée comme un seuil de littérature.
  omega3_marine boolean not null default false,
  iron_source boolean not null default false,
  calcium_source boolean not null default false,
  iodine_source boolean not null default false,
  zinc_source boolean not null default false,
  b12_source boolean not null default false,
  folate_source boolean not null default false,

  -- ── LA CUISSON ─────────────────────────────────────────────────────────
  -- La base porte la CLASSE, le module porte le FACTEUR. Éparpiller les
  -- nombres des deux côtés ferait diverger le jour où l'un des deux bouge, et
  -- c'est le module qui les teste.
  yield_class text not null check (yield_class in (
    'neutral',         -- rien n'absorbe ni ne perd
    'grain_absorbs',   -- riz, pâtes, semoule, quinoa
    'legume_absorbs',  -- légumineuses SÈCHES (une conserve est déjà hydratée)
    'meat_shrinks',    -- viandes et volailles
    'fish_shrinks',    -- poissons et fruits de mer
    'veg_shrinks'      -- légumes cuits
  )),

  -- Novotny 2012 et ses réplications: l'énergie métabolisable d'un fruit à
  -- coque ENTIER est ~72 % de sa valeur Atwater, la matrice cellulaire
  -- retenant une partie des lipides. L'effet disparaît quand la structure est
  -- détruite — les purées et beurres n'en portent pas.
  atwater_discount numeric not null default 1.0
    check (atwater_discount > 0 and atwater_discount <= 1),

  -- LA CLASSE QUI DÉCLENCHE L'ABSTENTION (FF-039 R6). Un seul terme dense non
  -- résolu suffit à rendre un repas non calculable: une matière grasse
  -- manquante déplace l'énergie d'un plat de plusieurs dizaines de pour cent,
  -- et un verdict rendu sans elle a l'air d'un résultat.
  energy_dense boolean not null default false,

  created_at timestamptz not null default now()
);

comment on table public.food_composition_refs is
  'FF-038: la composition d''un aliment pour 100 g CRUS. Donnée de RÉFÉRENCE '
  '(aucun user_id, donc hors lifecycle RGPD — voir le bloc GRANTS). Source '
  'ANSES-CIQUAL 2020 (Etalab) sauf source=''manual''. Ne remplace pas '
  'food_items, qui est un catalogue de libellés pour l''écran du coach.';

comment on column public.food_composition_refs.yield_class is
  'La classe de rendement cru→cuit. Le FACTEUR vit dans '
  '_shared/keel/food_composition.ts, en constante nommée et testée: deux '
  'copies d''un même nombre divergent, et c''est celle qu''on regarde le '
  'moins qui garde l''ancienne valeur.';

comment on column public.food_composition_refs.protein_g is
  'NULL = Ciqual ne donne pas la valeur. Jamais 0: un zéro se lirait « il n''y '
  'en a pas », ce que personne n''a affirmé. Le module propage l''inconnu.';

-- ── LA TABLE D'ALIAS — fermée, curée, jamais générée ─────────────────────
-- Le résolveur normalise le terme du générateur (`normalizeForMatch`, le
-- normaliseur des verrous, jamais un second), tente l'égalité exacte, puis
-- cette table. Un terme qui n'y est pas reste NON RÉSOLU et compté; il ne se
-- rapproche jamais « du plus proche ».
--
-- LA PK SUR `alias` EST UNE GARDE. Deux alias en conflit (même forme
-- normalisée, deux aliments) feraient un référentiel qui rend un résultat
-- différent selon l'ordre d'insertion. Mesuré pendant la curation: « pepper »
-- désignait le poivron ET le poivre. Il a été retiré des deux listes — un
-- terme ambigu doit rester non résolu, en garder un des deux serait
-- exactement la devinette que la fiche interdit.
create table if not exists public.food_composition_aliases (
  -- DÉJÀ NORMALISÉ à l'écriture (minuscules, sans diacritiques), parce que
  -- c'est sous cette forme que le résolveur interroge. Une table qui stocke
  -- des formes brutes serait illisible par son propre lecteur.
  alias text primary key,
  slug text not null references public.food_composition_refs(slug) on delete cascade,
  -- Pourquoi cet alias existe, quand ce n'est pas évident. Un alias ajouté
  -- doit être défendable en une phrase.
  note text
);

comment on table public.food_composition_aliases is
  'FF-038: forme normalisée -> slug de composition. FERMÉE et CURÉE: un terme '
  'absent reste non résolu et compté (unresolved_terms), jamais rapproché. '
  'La curation se pilote sur resolution_coverage.';

create index if not exists food_composition_aliases_slug_idx
  on public.food_composition_aliases (slug);

-- ---------------------------------------------------------------------------
-- LES GRANTS — service-role, et rien d'autre
--
-- Supabase accorde TOUT à `authenticated` sur toute table neuve, TRUNCATE
-- compris, et TRUNCATE échappe à RLS. `revoke ... from public` ne retire PAS
-- les privilèges d'`anon`, qui les tient de son propre grant. Les deux
-- cicatrices du dépôt, retirées nommément.
--
-- RLS activée SANS AUCUNE POLITIQUE: `service_role` la contourne, tout le
-- reste se heurte à un mur. C'est de la donnée de référence, personne ne la
-- lit depuis un JWT d'élève.
-- ---------------------------------------------------------------------------
revoke all on table public.food_composition_refs from anon, authenticated;
revoke all on table public.food_composition_aliases from anon, authenticated;
alter table public.food_composition_refs enable row level security;
alter table public.food_composition_aliases enable row level security;

-- ---------------------------------------------------------------------------
-- PAS DE RÉCLAMATION RGPD, ET C'EST UNE DÉCISION ÉCRITE
--
-- Ces deux tables ne portent AUCUNE donnée d'utilisateur: pas de `user_id`,
-- pas de FK vers `auth.users`, rien qui se rapporte à une personne. Elles
-- n'entrent donc ni dans `account-export-v1` ni dans la cascade de
-- suppression.
--
-- Le dépôt a la cicatrice INVERSE — « le lifecycle ne réclame pas les tables
-- neuves », neuf tables hors export. La parade n'est pas de tout réclamer:
-- c'est que chaque table neuve DISE laquelle des deux elle est. Celle-ci le
-- dit. La table de verdicts de FF-039, qui référence des repas d'un élève,
-- dira l'inverse et sera réclamée.
-- ---------------------------------------------------------------------------

-- ============================================================================
-- LE SEED — 208 aliments, 756 alias
--
-- GÉNÉRÉ par scratchpad/gen_composition_seed.py depuis l'XML Ciqual 2020, à
-- partir du catalogue curé de scratchpad/ciqual_catalogue.py. Ne pas éditer à
-- la main: régénérer, relire l'échantillon que le script imprime, recoller.
--
-- REJOUABLE. `on conflict do update` sur les deux tables: réappliquer cette
-- migration sur une base qui a déjà vécu RAFRAÎCHIT les valeurs au lieu
-- d'échouer. Ce chantier n'a pas de filet de reset — une migration qui ne
-- passe qu'une fois sur une base vierge est une migration cassée.
-- ============================================================================

insert into public.food_composition_refs
  (slug, food_group_ref, label, source, ciqual_code, ciqual_name,
   energy_kcal, protein_g, carbs_g, fat_g, fiber_g,
   omega3_marine, iron_source, calcium_source, iodine_source,
   zinc_source, b12_source, folate_source,
   yield_class, atwater_discount, energy_dense)
values
  ('beer', 'alcohol', 'Beer', 'ciqual', '5000', 'Bière brune', 18.1, 0.4, 4.1, 0.0, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('wine', 'alcohol', 'Wine', 'ciqual', '5214', 'Vin rouge', 82.1, 0.1, 2.6, 0.0, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('blueberries', 'berries', 'Blueberries', 'ciqual', '13028', 'Myrtille, crue', 57.7, 0.9, 10.6, 0.3, 2.4, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('mixed_berries', 'berries', 'Mixed berries', 'ciqual', '13997', 'Fruits rouges, crus (framboises, fraises, groseilles, cassis)', 49.4, 1.1, 7.9, 0.3, 5.3, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('raspberries', 'berries', 'Raspberries', 'ciqual', '13015', 'Framboise, crue', 49.2, 1.2, 5.8, 0.8, 4.3, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('strawberries', 'berries', 'Strawberries', 'ciqual', '13014', 'Fraise, crue', 38.6, 0.6, 6.0, null, 3.8, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('clementine', 'citrus', 'Clementine', 'ciqual', '13024', 'Clémentine ou Mandarine, pulpe, crue', 47.3, 0.8, 9.2, null, 1.7, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('grapefruit', 'citrus', 'Grapefruit', 'ciqual', '13614', 'Pamplemousse chinois, pulpe, cru', 39.9, 0.8, 8.6, 0.0, 1.0, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('lemon', 'citrus', 'Lemon', 'ciqual', '13009', 'Citron, pulpe, cru', 27.6, null, 1.6, null, null, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('lime', 'citrus', 'Lime', 'ciqual', '13067', 'Citron vert ou Lime, pulpe, cru', 40.2, 1.1, 3.1, null, 4.3, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('orange', 'citrus', 'Orange', 'ciqual', '13034', 'Orange, pulpe, crue', 45.5, 0.8, 8.0, null, 2.7, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('coffee', 'coffee_tea', 'Coffee', 'ciqual', '18004', 'Café, non instantané, non sucré, prêt à boire', 6.9, null, 1.4, 0.0, null, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('tea', 'coffee_tea', 'Tea', 'ciqual', '18020', 'Thé infusé, non sucré', 0.1, 0.0, 0.0, 0.0, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('broccoli', 'cruciferous_veg', 'Broccoli', 'ciqual', '20057', 'Brocoli, cru', 32.7, 4.0, 1.7, 0.5, 2.9, false, false, false, false, false, false, true, 'veg_shrinks', 1.0, false),
  ('brussels_sprouts', 'cruciferous_veg', 'Brussels sprouts', 'ciqual', '20058', 'Chou de Bruxelles, cru', 50.1, 4.0, 5.7, 0.4, 4.0, false, false, false, false, false, false, true, 'veg_shrinks', 1.0, false),
  ('cabbage', 'cruciferous_veg', 'Cabbage', 'ciqual', '20069', 'Chou vert, cru', 27.6, 2.5, 1.9, 0.4, 3.1, false, false, false, false, false, false, true, 'veg_shrinks', 1.0, false),
  ('cauliflower', 'cruciferous_veg', 'Cauliflower', 'ciqual', '20016', 'Chou-fleur, cru', 26.2, 1.8, 2.1, 0.7, 2.2, false, false, false, false, false, false, true, 'veg_shrinks', 1.0, false),
  ('kale', 'cruciferous_veg', 'Kale', 'ciqual', '20218', 'Chou frisé, cru', 53.6, 4.3, 4.2, 1.1, 4.9, false, false, true, false, false, false, true, 'veg_shrinks', 1.0, false),
  ('pak_choi', 'cruciferous_veg', 'Pak choi', 'ciqual', '20167', 'Chou chinois ou pak-choi ou pé-tsai, cru', 16.0, 1.4, 1.6, 0.2, 1.1, false, false, false, false, false, false, true, 'veg_shrinks', 1.0, false),
  ('radish', 'cruciferous_veg', 'Radish', 'ciqual', '20089', 'Radis noir, cru', 29.2, 0.9, 5.5, null, 1.2, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('red_cabbage', 'cruciferous_veg', 'Red cabbage', 'ciqual', '20014', 'Chou rouge, cru', 30.0, 1.1, 4.3, null, 2.8, false, false, false, false, false, false, true, 'veg_shrinks', 1.0, false),
  ('cheddar', 'dairy_cheese', 'Cheddar', 'ciqual', '12726', 'Cheddar', 399.0, 24.0, 0.0, 33.8, 0.0, false, false, true, true, true, true, false, 'neutral', 1.0, false),
  ('cream_cheese', 'dairy_cheese', 'Cream cheese', 'manual', null, null, 253.0, 6.0, 4.0, 24.0, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, true),
  ('feta', 'dairy_cheese', 'Feta', 'ciqual', '12066', 'Feta AOP', 285.0, 15.1, 0.7, 24.3, 0.0, false, false, true, true, false, true, false, 'neutral', 1.0, false),
  ('goat_cheese', 'dairy_cheese', 'Goat cheese', 'ciqual', '21800', 'Chevreau, cru', 103.0, 20.6, 0.0, 2.3, 0.0, false, true, false, false, true, true, false, 'neutral', 1.0, false),
  ('halloumi', 'dairy_cheese', 'Halloumi', 'manual', null, null, 321.0, 22.0, 2.2, 25.0, 0.0, false, false, true, false, false, true, false, 'neutral', 1.0, false),
  ('mozzarella', 'dairy_cheese', 'Mozzarella', 'ciqual', '19590', 'Mozzarella au lait de vache', 227.0, 16.5, 0.8, 17.7, 0.0, false, false, true, true, true, true, false, 'neutral', 1.0, false),
  ('parmesan', 'dairy_cheese', 'Parmesan', 'ciqual', '12120', 'Parmesan', 406.0, 31.1, 0.0, 31.0, 0.0, false, false, true, true, true, true, false, 'neutral', 1.0, false),
  ('cottage_cheese', 'dairy_yogurt', 'Cottage cheese', 'manual', null, null, 98.0, 11.1, 3.4, 4.3, 0.0, false, false, false, false, false, true, false, 'neutral', 1.0, false),
  ('fromage_blanc', 'dairy_yogurt', 'Fromage blanc', 'ciqual', '19646', 'Fromage blanc nature, 3% MG environ', 76.9, 8.0, 3.5, 3.3, 0.0, false, false, true, false, false, true, false, 'neutral', 1.0, false),
  ('greek_yogurt', 'dairy_yogurt', 'Greek yogurt', 'ciqual', '19860', 'Yaourt à la grecque, nature', 113.1, 3.3, 4.2, 9.2, null, false, false, true, false, false, false, false, 'neutral', 1.0, false),
  ('kefir', 'dairy_yogurt', 'Kefir', 'ciqual', '19865', 'Kéfir de lait', 62.3, 3.2, 4.5, 3.5, 0.0, false, false, true, true, false, false, false, 'neutral', 1.0, false),
  ('milk_semi', 'dairy_yogurt', 'Semi-skimmed milk', 'manual', null, null, 46.0, 3.3, 4.8, 1.6, 0.0, false, false, true, false, false, true, false, 'neutral', 1.0, false),
  ('plain_yogurt', 'dairy_yogurt', 'Plain yogurt', 'manual', null, null, 59.0, 3.5, 4.7, 3.3, 0.0, false, false, true, false, false, true, false, 'neutral', 1.0, false),
  ('skyr', 'dairy_yogurt', 'Skyr', 'manual', null, null, 63.0, 11.0, 4.0, 0.2, 0.0, false, false, true, false, false, true, false, 'neutral', 1.0, false),
  ('egg_white', 'eggs', 'Egg white', 'ciqual', '22001', 'Oeuf, blanc (blanc d''oeuf), cru', 48.1, 10.8, 0.8, 0.2, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('egg_yolk', 'eggs', 'Egg yolk', 'ciqual', '22002', 'Oeuf, jaune (jaune d''oeuf), cru', 307.0, 15.5, 1.1, 26.7, 0.0, false, false, false, true, false, true, true, 'neutral', 1.0, true),
  ('whole_eggs', 'eggs', 'Eggs', 'ciqual', '22000', 'Oeuf, cru', 140.0, 12.7, 0.3, 9.8, 0.0, false, false, false, false, false, true, true, 'neutral', 1.0, false),
  ('anchovy', 'fatty_fish', 'Anchovies', 'ciqual', '26000', 'Anchois, filets à l''huile, semi-conserve, égoutté', 182.0, 26.4, null, 8.4, null, true, true, true, true, true, true, false, 'neutral', 1.0, false),
  ('herring', 'fatty_fish', 'Herring', 'ciqual', '26011', 'Hareng, cru', 176.0, 17.7, 0.0, 11.7, 0.0, true, false, false, true, false, true, false, 'fish_shrinks', 1.0, false),
  ('mackerel', 'fatty_fish', 'Mackerel', 'ciqual', '26051', 'Maquereau, cru', 194.0, 18.1, 0.0, 13.5, 0.0, true, false, false, true, false, true, false, 'fish_shrinks', 1.0, false),
  ('salmon', 'fatty_fish', 'Salmon', 'ciqual', '26036', 'Saumon, cru, élevage', 194.0, 20.5, 0.0, 12.4, null, true, false, false, false, false, true, false, 'fish_shrinks', 1.0, false),
  ('sardines', 'fatty_fish', 'Sardines', 'ciqual', '26034', 'Sardine, à l''huile, appertisée, égouttée', 207.0, 24.4, 0.5, 12.0, 0.0, true, false, true, true, true, true, false, 'neutral', 1.0, false),
  ('smoked_salmon', 'fatty_fish', 'Smoked salmon', 'ciqual', '26037', 'Saumon fumé', 178.0, 22.0, 0.9, 9.5, null, true, false, false, true, false, true, false, 'neutral', 1.0, false),
  ('trout', 'fatty_fish', 'Trout', 'ciqual', '26092', 'Truite de mer, crue', 111.0, 19.6, 0.0, 3.6, 0.0, false, false, false, false, false, true, false, 'fish_shrinks', 1.0, false),
  ('chips_fries', 'fried_food', 'Chips / fries', 'ciqual', '4030', 'Frites de pommes de terre, surgelées, rôties/cuites au four', 213.0, 3.8, 32.6, 6.6, 4.2, false, false, false, false, false, false, true, 'neutral', 1.0, true),
  ('crisps', 'fried_food', 'Crisps', 'ciqual', '4004', 'Chips de pommes de terre nature ou aromatisées, standard', 545.0, 5.7, 51.1, 34.3, 4.6, false, false, false, false, false, false, true, 'neutral', 1.0, true),
  ('herbs_basil', 'leafy_greens', 'Basil', 'ciqual', '11033', 'Basilic, frais', 34.8, 3.4, 2.5, 0.5, 3.5, false, true, true, false, false, false, true, 'neutral', 1.0, false),
  ('herbs_coriander', 'leafy_greens', 'Coriander', 'ciqual', '11094', 'Coriandre, fraiche', 22.3, 2.1, 0.9, 0.5, 2.8, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('herbs_mint', 'leafy_greens', 'Mint', 'ciqual', '11027', 'Menthe, fraîche', 57.6, 3.5, 5.3, 0.8, 7.4, false, true, true, false, false, false, true, 'neutral', 1.0, false),
  ('herbs_parsley', 'leafy_greens', 'Parsley', 'ciqual', '11014', 'Persil, frais', 43.0, 3.7, 3.5, 0.6, 4.3, false, true, true, false, false, false, true, 'neutral', 1.0, false),
  ('herbs_thyme', 'leafy_greens', 'Thyme', 'ciqual', '11038', 'Thym, séché', 285.0, 9.1, 26.9, 7.4, 37.0, false, true, true, false, true, false, true, 'neutral', 1.0, false),
  ('lettuce', 'leafy_greens', 'Lettuce', 'ciqual', '20031', 'Laitue, crue', 14.7, 1.3, 1.3, 0.2, 1.2, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('rocket', 'leafy_greens', 'Rocket', 'ciqual', '20217', 'Roquette, crue', 27.9, 2.6, 2.1, 0.7, 1.6, false, false, true, false, false, false, true, 'neutral', 1.0, false),
  ('spinach', 'leafy_greens', 'Spinach', 'ciqual', '20059', 'Épinard, cru', 28.7, 2.6, 2.2, 0.5, 2.4, false, true, false, false, false, false, true, 'veg_shrinks', 1.0, false),
  ('swiss_chard', 'leafy_greens', 'Swiss chard', 'ciqual', '20004', 'Bette ou blette, crue', 16.4, 1.0, 1.6, null, 1.8, false, false, false, false, false, false, false, 'veg_shrinks', 1.0, false),
  ('watercress', 'leafy_greens', 'Watercress', 'ciqual', '20199', 'Cresson alénois, cru', 27.1, 2.5, 2.2, 0.6, 1.4, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('ham', 'lean_protein', 'Ham', 'ciqual', '28803', 'Jambon cuit, fumé', 135.0, 20.0, 0.8, 5.8, 0.1, false, false, false, false, true, false, false, 'neutral', 1.0, false),
  ('pork_loin', 'lean_protein', 'Pork loin', 'ciqual', '28204', 'Porc, filet mignon, cru', 123.0, 21.2, 0.4, 4.1, 0.0, false, false, false, false, true, false, false, 'meat_shrinks', 1.0, false),
  ('turkey_breast', 'lean_protein', 'Turkey breast', 'ciqual', '36304', 'Dinde, escalope, crue', 109.0, 24.1, 0.5, 1.2, 0.0, false, false, false, false, false, true, false, 'meat_shrinks', 1.0, false),
  ('baked_beans', 'legumes', 'Baked beans', 'manual', null, null, 94.0, 4.8, 15.0, 0.6, 4.9, false, true, false, false, false, false, false, 'neutral', 1.0, false),
  ('black_beans', 'legumes', 'Black beans', 'manual', null, null, 132.0, 8.9, 23.7, 0.5, 8.7, false, true, false, false, false, false, true, 'neutral', 1.0, false),
  ('broad_beans', 'legumes', 'Broad beans', 'ciqual', '20500', 'Fève, bouillie/cuite à l''eau', 82.9, 8.1, 9.3, 0.8, 3.1, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('chickpeas_dry', 'legumes', 'Chickpeas (dry)', 'ciqual', '20516', 'Pois chiche, sec', 351.2, 20.5, 47.5, 5.8, 13.3, false, true, false, false, true, false, true, 'legume_absorbs', 1.0, false),
  ('chickpeas_tinned', 'legumes', 'Chickpeas (tinned)', 'ciqual', '20532', 'Pois chiche, appertisé, égoutté', 122.0, 6.7, 15.0, 2.7, 5.5, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('edamame', 'legumes', 'Edamame', 'manual', null, null, 121.0, 12.0, 8.9, 5.2, 5.2, false, true, false, false, false, false, true, 'neutral', 1.0, false),
  ('green_peas', 'legumes', 'Peas', 'ciqual', '20037', 'Petits pois, cuits', 61.4, 5.8, 4.7, 0.9, 5.8, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('hummus', 'legumes', 'Hummus', 'ciqual', '25621', 'Houmous, préemballé', 288.3, 8.2, 7.1, 23.9, 6.0, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('kidney_beans', 'legumes', 'Kidney beans', 'ciqual', '20524', 'Haricot rouge, appertisé, égoutté', 108.0, 8.3, 13.0, 1.0, 7.0, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('lentils_cooked', 'legumes', 'Lentils (cooked)', 'ciqual', '20505', 'Lentille, bouillie/cuite à l''eau', 104.1, 9.0, 12.2, 0.4, 7.9, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('lentils_dry', 'legumes', 'Lentils (dry)', 'ciqual', '20504', 'Lentille, sèche', 331.3, 25.4, 50.6, 1.3, 7.6, false, true, false, false, true, false, true, 'legume_absorbs', 1.0, false),
  ('white_beans', 'legumes', 'White beans', 'ciqual', '20511', 'Haricot blanc, appertisé, égoutté', 87.5, 6.6, 10.9, 0.4, 7.0, false, true, false, false, false, false, true, 'neutral', 1.0, false),
  ('asparagus', 'non_starchy_veg', 'Asparagus', 'ciqual', '20073', 'Asperge, pelée, crue', 23.5, 2.0, 2.4, 0.2, 1.9, false, false, false, false, false, false, true, 'veg_shrinks', 1.0, false),
  ('aubergine', 'non_starchy_veg', 'Aubergine', 'ciqual', '20053', 'Aubergine, crue', 20.7, 1.1, 2.4, 0.1, 2.7, false, false, false, false, false, false, false, 'veg_shrinks', 1.0, false),
  ('bell_pepper', 'non_starchy_veg', 'Bell pepper', 'ciqual', '20085', 'Poivron vert, cru', 26.0, 0.8, 3.4, null, 3.2, false, false, false, false, false, false, true, 'veg_shrinks', 1.0, false),
  ('carrot', 'non_starchy_veg', 'Carrot', 'ciqual', '20009', 'Carotte, crue', 40.2, 0.6, 7.6, null, 2.7, false, false, false, false, false, false, true, 'veg_shrinks', 1.0, false),
  ('celery', 'non_starchy_veg', 'Celery', 'ciqual', '20023', 'Céleri branche, cru', 17.6, 0.6, 2.4, null, 2.2, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('chilli', 'non_starchy_veg', 'Chilli', 'ciqual', '20151', 'Piment, cru', 44.5, 1.9, 7.7, 0.3, 1.6, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('courgette', 'non_starchy_veg', 'Courgette', 'ciqual', '20020', 'Courgette, pulpe et peau, crue', 16.5, 1.2, 1.8, 0.3, 1.1, false, false, false, false, false, false, true, 'veg_shrinks', 1.0, false),
  ('cucumber', 'non_starchy_veg', 'Cucumber', 'ciqual', '20210', 'Concombre, pulpe, cru', 14.7, 0.6, 2.2, null, 0.8, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('fennel', 'non_starchy_veg', 'Fennel', 'ciqual', '20028', 'Fenouil, cru', 21.8, 1.0, 2.6, null, 2.6, false, false, false, false, false, false, false, 'veg_shrinks', 1.0, false),
  ('garlic', 'non_starchy_veg', 'Garlic', 'ciqual', '11000', 'Ail, cru', 111.0, 5.3, 18.6, null, 5.8, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('ginger', 'non_starchy_veg', 'Ginger', 'ciqual', '11074', 'Gingembre, racine crue', 32.9, 1.1, 3.4, 1.1, 2.7, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('green_beans', 'non_starchy_veg', 'Green beans', 'ciqual', '20061', 'Haricot vert, cru', 31.6, 1.9, 4.1, 0.2, 2.9, false, false, false, false, false, false, true, 'veg_shrinks', 1.0, false),
  ('leek', 'non_starchy_veg', 'Leek', 'ciqual', '20039', 'Poireau, cru', 32.3, 1.5, 4.9, 0.2, 2.3, false, false, false, false, false, false, true, 'veg_shrinks', 1.0, false),
  ('mushroom', 'non_starchy_veg', 'Mushrooms', 'ciqual', '20056', 'Champignon de Paris ou champignon de couche, cru', 28.0, 2.6, 3.1, 0.4, 1.0, false, false, false, false, false, false, true, 'veg_shrinks', 1.0, false),
  ('olives', 'non_starchy_veg', 'Olives', 'ciqual', '13186', 'Olive noire (aliment moyen)', 195.6, 1.5, 0.1, 19.5, 7.0, false, true, false, false, false, false, false, 'neutral', 1.0, true),
  ('onion', 'non_starchy_veg', 'Onion', 'ciqual', '20034', 'Oignon, cru', 38.4, 1.1, 6.2, 0.6, 1.7, false, false, false, false, false, false, false, 'veg_shrinks', 1.0, false),
  ('passata', 'non_starchy_veg', 'Passata', 'ciqual', '20170', 'Tomate, purée, appertisée', 47.1, 1.4, 7.5, 0.4, 2.4, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('peas_frozen', 'non_starchy_veg', 'Frozen mixed vegetables', 'ciqual', '20101', 'Légumes, mélange surgelé, crus', 65.1, 2.3, 5.7, 2.6, 4.7, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('spring_onion', 'non_starchy_veg', 'Spring onion', 'ciqual', '11003', 'Ciboule ou Ciboulette, fraîche', 29.7, 2.6, 2.1, 0.5, 3.2, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('tinned_tomatoes', 'non_starchy_veg', 'Tinned tomatoes', 'ciqual', '20048', 'Tomate, pelée, appertisée, égouttée', 18.3, 1.1, 1.9, 0.3, 1.3, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('tomato', 'non_starchy_veg', 'Tomato', 'ciqual', '20047', 'Tomate, crue', 19.3, 0.9, 2.5, 0.3, 1.2, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('tomato_puree', 'non_starchy_veg', 'Tomato purée', 'ciqual', '20068', 'Tomate, concentré, appertisé', 99.2, 4.4, 17.1, 0.5, 4.2, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('almonds', 'nuts_seeds', 'Almonds', 'ciqual', '15000', 'Amande (avec peau)', 599.9, 18.8, 9.5, 51.3, 12.5, false, true, true, false, true, false, true, 'neutral', 0.72, true),
  ('cashews', 'nuts_seeds', 'Cashews', 'ciqual', '15019', 'Noix de cajou, grillée, salée', 620.8, 15.2, 26.7, 49.5, 3.9, false, true, false, false, true, false, true, 'neutral', 0.72, true),
  ('chia_seeds', 'nuts_seeds', 'Chia seeds', 'ciqual', '15047', 'Chia, graine, séchée', 442.0, 16.5, 7.7, 30.7, 34.4, false, true, true, false, true, false, true, 'neutral', 1.0, true),
  ('flaxseed', 'nuts_seeds', 'Flaxseed', 'ciqual', '15034', 'Lin, graine', 491.2, 20.2, 6.6, 36.6, 27.3, false, true, true, false, true, false, true, 'neutral', 1.0, true),
  ('hazelnuts', 'nuts_seeds', 'Hazelnuts', 'ciqual', '15004', 'Noisette', 621.5, 14.4, 7.2, 56.9, 11.6, false, true, true, false, true, false, true, 'neutral', 0.72, true),
  ('mixed_nuts', 'nuts_seeds', 'Mixed nuts', 'manual', null, null, 607.0, 18.0, 13.0, 53.0, 7.5, false, true, false, false, true, false, false, 'neutral', 0.72, true),
  ('peanut_butter', 'nuts_seeds', 'Peanut butter', 'ciqual', '15202', 'Beurre de cacahuète ou Pâte d''arachide', 635.7, 22.2, 16.1, 52.5, 5.0, false, false, false, false, true, false, true, 'neutral', 1.0, true),
  ('peanuts', 'nuts_seeds', 'Peanuts', 'ciqual', '15001', 'Cacahuète ou Arachide', 609.5, 22.8, 14.8, 49.1, 8.6, false, false, false, false, true, false, true, 'neutral', 0.72, true),
  ('pumpkin_seeds', 'nuts_seeds', 'Pumpkin seeds', 'manual', null, null, 559.0, 30.2, 10.7, 49.0, 6.0, false, true, false, false, true, false, true, 'neutral', 1.0, true),
  ('sesame_seeds', 'nuts_seeds', 'Sesame seeds', 'ciqual', '15010', 'Sésame, graine', 586.9, 17.6, 9.8, 49.7, 14.9, false, true, true, false, true, false, true, 'neutral', 1.0, true),
  ('sunflower_seeds', 'nuts_seeds', 'Sunflower seeds', 'ciqual', '15011', 'Tournesol, graine', 637.9, 21.3, 10.1, 55.5, 6.4, false, true, false, false, true, false, true, 'neutral', 1.0, true),
  ('tahini', 'nuts_seeds', 'Tahini', 'ciqual', '15203', 'Tahin ou Purée de sésame', 620.6, 17.7, 13.8, 53.4, 7.0, false, true, true, false, true, false, true, 'neutral', 1.0, true),
  ('walnuts', 'nuts_seeds', 'Walnuts', 'ciqual', '15023', 'Noix, fraîche', 377.8, 11.0, 9.9, 31.8, 3.9, false, false, false, false, true, false, true, 'neutral', 0.72, true),
  ('olive_oil', 'olive_oil', 'Olive oil', 'ciqual', '17270', 'Huile d''olive vierge extra', 900.0, null, 0.0, 99.9, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, true),
  ('butter', 'other_added_fat', 'Butter', 'ciqual', '16400', 'Beurre à 82% MG, doux', 753.0, 0.7, 0.9, 82.9, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, true),
  ('coconut_milk', 'other_added_fat', 'Coconut milk', 'ciqual', '18041', 'Lait de coco ou Crème de coco', 188.0, 1.8, 3.4, 18.4, 0.6, false, true, false, false, false, false, false, 'neutral', 1.0, true),
  ('coconut_oil', 'other_added_fat', 'Coconut oil', 'manual', null, null, 890.0, 0.0, 0.0, 99.0, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, true),
  ('creme_fraiche', 'other_added_fat', 'Crème fraîche', 'manual', null, null, 292.0, 2.4, 2.9, 30.0, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, true),
  ('ghee', 'other_added_fat', 'Ghee', 'ciqual', '16401', 'Huile de beurre ou Beurre concentré', 900.2, 0.3, 0.0, 99.9, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, true),
  ('rapeseed_oil', 'other_added_fat', 'Rapeseed oil', 'ciqual', '17130', 'Huile de colza', 900.0, 0.0, 0.0, 100.0, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, true),
  ('sesame_oil', 'other_added_fat', 'Sesame oil', 'ciqual', '17400', 'Huile de sésame', 900.0, 0.0, 0.0, 100.0, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, true),
  ('single_cream', 'other_added_fat', 'Cream', 'ciqual', '19430', 'Crème de lait, 15 à 20% MG, légère, semi-épaisse, UHT', 194.0, 2.6, 2.9, 18.7, null, false, false, false, false, false, false, false, 'neutral', 1.0, true),
  ('sunflower_oil', 'other_added_fat', 'Sunflower oil', 'ciqual', '17440', 'Huile de tournesol', 901.0, null, 0.0, 100.0, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, true),
  ('apple', 'other_fruit', 'Apple', 'ciqual', '13050', 'Pomme, pulpe, crue', 47.6, 0.3, 10.7, 0.1, 1.3, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('avocado', 'other_fruit', 'Avocado', 'ciqual', '13004', 'Avocat, pulpe, cru', 205.0, 1.6, 0.8, 20.6, 3.6, false, false, false, false, false, false, true, 'neutral', 1.0, true),
  ('banana', 'other_fruit', 'Banana', 'ciqual', '13005', 'Banane, pulpe, crue', 90.5, 1.1, 19.7, null, 2.7, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('dates', 'other_fruit', 'Dates', 'ciqual', '13011', 'Datte, pulpe et peau, sèche', 282.9, 1.8, 64.7, 0.2, 7.3, false, false, false, false, false, false, false, 'neutral', 1.0, true),
  ('dried_apricot', 'other_fruit', 'Dried apricots', 'manual', null, null, 241.0, 3.4, 53.0, 0.5, 7.3, false, true, false, false, false, false, false, 'neutral', 1.0, true),
  ('grapes', 'other_fruit', 'Grapes', 'ciqual', '13112', 'Raisin, cru', 68.9, 0.7, 15.7, 0.2, 0.9, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('kiwi', 'other_fruit', 'Kiwi', 'ciqual', '13021', 'Kiwi, pulpe et graines, cru', 60.5, 0.9, 11.0, 0.6, 2.4, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('mango', 'other_fruit', 'Mango', 'ciqual', '13025', 'Mangue, pulpe, crue', 73.9, 0.6, 14.3, null, 1.6, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('melon', 'other_fruit', 'Melon', 'ciqual', '13742', 'Melon miel ou melon honeydew, pulpe, cru', 22.6, 0.6, 4.3, 0.2, 0.8, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('peach', 'other_fruit', 'Peach', 'ciqual', '13195', 'Pêche jaune, pulpe, crue', 46.3, 0.7, 9.8, null, 1.0, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('pear', 'other_fruit', 'Pear', 'ciqual', '20039', 'Poireau, cru', 32.3, 1.5, 4.9, 0.2, 2.3, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('pineapple', 'other_fruit', 'Pineapple', 'ciqual', '13002', 'Ananas, pulpe, cru', 54.4, null, 11.7, null, 1.2, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('raisins', 'other_fruit', 'Raisins', 'ciqual', '13046', 'Raisin, sec', 321.0, 3.0, 73.2, 0.9, 4.2, false, false, false, false, false, false, true, 'neutral', 1.0, true),
  ('chicken_breast', 'poultry', 'Chicken breast', 'ciqual', '36017', 'Poulet, filet, sans peau, cru', 110.0, 23.4, 0.0, 1.5, 0.0, false, false, false, false, false, false, false, 'meat_shrinks', 1.0, false),
  ('chicken_thigh', 'poultry', 'Chicken thigh', 'ciqual', '36024', 'Poulet, cuisse, viande, cru', 114.0, 19.3, 0.0, 4.0, 0.0, false, false, false, false, true, true, false, 'meat_shrinks', 1.0, false),
  ('duck_breast', 'poultry', 'Duck breast', 'ciqual', '36206', 'Canard, magret, cru', 340.0, 17.9, 0.8, 29.4, 0.0, false, false, false, false, false, false, false, 'meat_shrinks', 1.0, false),
  ('turkey_mince', 'poultry', 'Turkey mince', 'ciqual', '36301', 'Dinde, viande, crue', 110.0, 22.4, 0.8, 1.9, 0.0, false, false, false, false, true, true, false, 'meat_shrinks', 1.0, false),
  ('bacon', 'red_meat', 'Bacon', 'ciqual', '28720', 'Lardon fumé, cru', 275.0, 16.7, 1.0, 22.6, 0.3, false, false, false, false, false, true, false, 'meat_shrinks', 1.0, false),
  ('beef_braising', 'red_meat', 'Braising beef', 'ciqual', '6270', 'Boeuf, paleron, cru', 144.0, 21.2, 0.0, 6.5, 0.0, false, true, false, false, true, true, false, 'meat_shrinks', 1.0, false),
  ('beef_mince', 'red_meat', 'Beef mince (5%)', 'ciqual', '6250', 'Boeuf, steak haché 5% MG, cru', 130.0, 21.9, 0.3, 4.6, 0.0, false, true, false, false, true, true, false, 'meat_shrinks', 1.0, false),
  ('beef_steak', 'red_meat', 'Beef steak', 'ciqual', '6201', 'Boeuf, steak ou bifteck, cru', 223.0, 19.2, 0.0, 16.2, 0.0, false, false, false, false, true, true, false, 'meat_shrinks', 1.0, false),
  ('chorizo', 'red_meat', 'Chorizo', 'ciqual', '30315', 'Chorizo', 433.0, 23.5, 3.0, 36.1, 0.9, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('lamb', 'red_meat', 'Lamb', 'ciqual', '21502', 'Agneau, gigot, cru', 128.0, 20.0, 0.5, 5.1, 0.0, false, false, false, false, true, true, false, 'meat_shrinks', 1.0, false),
  ('pork_chop', 'red_meat', 'Pork chop', 'ciqual', '28100', 'Porc, côte, crue', 164.0, 19.8, 0.4, 9.3, 0.0, false, false, false, false, true, false, false, 'meat_shrinks', 1.0, false),
  ('sausage', 'red_meat', 'Sausage', 'ciqual', '30110', 'Saucisse de Toulouse, crue', 327.0, 13.2, 1.0, 30.0, 0.0, false, false, false, false, true, false, false, 'meat_shrinks', 1.0, false),
  ('breakfast_cereal', 'refined_grain', 'Breakfast cereal', 'ciqual', '32003', 'Céréales pour petit déjeuner (aliment moyen)', 398.0, 7.8, 75.3, 6.1, 5.2, false, true, true, true, false, true, true, 'neutral', 1.0, false),
  ('cooked_rice', 'refined_grain', 'Cooked rice', 'ciqual', '9104', 'Riz blanc, cuit, non salé', 145.0, 2.9, 31.8, 0.4, 0.8, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('couscous', 'refined_grain', 'Couscous', 'ciqual', '9610', 'Semoule de blé dur, crue', 352.0, 10.9, 71.6, 1.2, 3.4, false, false, false, false, true, false, true, 'grain_absorbs', 1.0, false),
  ('granola', 'refined_grain', 'Granola', 'ciqual', '32004', 'Muesli (aliment moyen)', 418.0, 7.5, 66.6, 12.2, 6.4, false, true, false, true, true, true, true, 'neutral', 1.0, true),
  ('noodles', 'refined_grain', 'Noodles', 'ciqual', '25183', 'Nouilles sautées/poêlées aux crevettes', 104.0, 4.9, 12.6, 3.4, 1.6, false, false, false, false, false, false, true, 'grain_absorbs', 1.0, false),
  ('polenta', 'refined_grain', 'Polenta', 'ciqual', '9614', 'Polenta ou semoule de maïs, précuite, sèche', 350.0, 7.9, 74.0, 1.8, 3.2, false, false, false, false, false, false, true, 'grain_absorbs', 1.0, false),
  ('white_bread', 'refined_grain', 'White bread', 'ciqual', '7112', 'Pain de mie, au son', 278.0, 6.8, 46.0, 5.5, 7.0, false, true, false, false, false, false, false, 'neutral', 1.0, false),
  ('white_pasta', 'refined_grain', 'Pasta', 'ciqual', '9810', 'Pâtes sèches standard, crues', 336.0, 11.5, 65.8, 1.8, 3.0, false, false, false, false, false, false, false, 'grain_absorbs', 1.0, false),
  ('white_rice', 'refined_grain', 'White rice', 'ciqual', '9100', 'Riz blanc, cru', 352.0, 7.0, 78.0, 0.9, 1.1, false, false, false, false, false, false, false, 'grain_absorbs', 1.0, false),
  ('black_pepper', 'sauce_dressing', 'Black pepper', 'ciqual', '11015', 'Poivre noir, poudre', 330.0, 13.3, 39.5, 7.5, 25.7, false, true, true, false, false, false, false, 'neutral', 1.0, false),
  ('chilli_powder', 'sauce_dressing', 'Chilli powder', 'manual', null, null, 282.0, 12.0, 30.0, 14.0, 28.0, false, true, false, false, false, false, false, 'neutral', 1.0, false),
  ('cinnamon', 'sauce_dressing', 'Cinnamon', 'ciqual', '11025', 'Cannelle, poudre', 243.0, 3.9, 27.5, 1.2, 53.1, false, true, true, false, true, false, false, 'neutral', 1.0, false),
  ('cumin', 'sauce_dressing', 'Cumin', 'ciqual', '11042', 'Cumin, graine', 427.0, 17.8, 33.7, 22.3, 10.5, false, true, true, false, true, false, false, 'neutral', 1.0, false),
  ('curry_paste', 'sauce_dressing', 'Curry paste', 'ciqual', '11005', 'Curry, poudre', 301.0, 14.5, 2.6, 14.0, 53.2, false, true, true, false, true, false, true, 'neutral', 1.0, false),
  ('ketchup', 'sauce_dressing', 'Ketchup', 'ciqual', '11008', 'Ketchup, préemballé', 99.0, 1.3, 21.4, 0.2, 1.1, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('mayonnaise', 'sauce_dressing', 'Mayonnaise', 'ciqual', '11054', 'Mayonnaise (70% MG min.), préemballée', 693.4, 1.4, 2.6, 75.2, 0.3, false, false, false, true, false, true, false, 'neutral', 1.0, true),
  ('mustard', 'sauce_dressing', 'Mustard', 'ciqual', '11013', 'Moutarde', 152.0, 6.9, 4.3, 11.2, null, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('paprika', 'sauce_dressing', 'Paprika', 'ciqual', '11049', 'Paprika', 319.0, 14.1, 19.1, 12.9, 34.9, false, true, true, false, true, false, true, 'neutral', 1.0, false),
  ('pesto', 'sauce_dressing', 'Pesto', 'ciqual', '11179', 'Sauce pesto, préemballée', 370.0, 3.9, 6.6, 35.4, 2.5, false, false, true, false, false, false, false, 'neutral', 1.0, true),
  ('salsa', 'sauce_dressing', 'Salsa', 'manual', null, null, 36.0, 1.3, 6.6, 0.2, 1.5, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('salt', 'sauce_dressing', 'Salt', 'ciqual', '11058', 'Sel blanc alimentaire, iodé, non fluoré (marin, ignigène ou gemme)', 0.0, 0.0, 0.0, 0.0, 0.0, false, false, false, true, false, false, false, 'neutral', 1.0, false),
  ('soy_sauce', 'sauce_dressing', 'Soy sauce', 'ciqual', '11104', 'Sauce soja, préemballée', 45.5, 7.1, 3.6, 0.1, 0.9, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('stock_cube', 'sauce_dressing', 'Stock', 'ciqual', '11001', 'Bouillon de boeuf, déshydraté', 240.0, 10.2, 19.7, 13.3, 0.7, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('vinaigrette', 'sauce_dressing', 'Vinaigrette', 'ciqual', '11110', 'Sauce vinaigrette (50 à 75% d''huile), préemballée', 492.7, 0.5, 4.6, 52.4, 0.3, false, false, false, false, false, false, false, 'neutral', 1.0, true),
  ('vinegar', 'sauce_dressing', 'Vinegar', 'ciqual', '11018', 'Vinaigre', 22.6, 0.0, 0.6, 0.1, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('crab', 'shellfish', 'Crab', 'ciqual', '10025', 'Crabe ou Tourteau, bouilli/cuit à l''eau', 124.0, 19.5, 1.8, 4.3, 0.0, true, false, false, true, true, true, false, 'neutral', 1.0, false),
  ('mussels', 'shellfish', 'Mussels', 'ciqual', '10013', 'Moule, bouillie/cuite à l''eau', 108.0, 17.2, 5.1, 2.1, 0.0, true, true, false, true, true, true, true, 'neutral', 1.0, false),
  ('prawns', 'shellfish', 'Prawns', 'ciqual', '10007', 'Crevette, cuite', 93.8, 19.0, 1.9, 1.2, 0.0, true, false, true, false, true, true, false, 'neutral', 1.0, false),
  ('scallops', 'shellfish', 'Scallops', 'ciqual', '10045', 'Coquille Saint-Jacques, noix, crue', 83.6, 17.9, 1.1, 0.8, 0.0, false, false, false, true, true, true, false, 'fish_shrinks', 1.0, false),
  ('squid', 'shellfish', 'Squid', 'ciqual', '10001', 'Calmar ou calamar ou encornet, cru', 77.0, 14.4, 2.2, 1.2, 0.0, true, false, false, false, false, true, false, 'fish_shrinks', 1.0, false),
  ('beetroot', 'starchy_veg', 'Beetroot', 'ciqual', '20003', 'Betterave rouge, cuite', 42.8, 1.4, 7.1, 0.4, 2.5, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('butternut_squash', 'starchy_veg', 'Butternut squash', 'ciqual', '20044', 'Potiron, cru', 19.9, 1.0, 3.5, 0.1, 0.5, false, false, false, false, false, false, false, 'veg_shrinks', 1.0, false),
  ('parsnip', 'starchy_veg', 'Parsnip', 'ciqual', '20181', 'Panais, cru', 58.3, 1.5, 10.1, 0.4, 4.7, false, false, false, false, false, false, true, 'veg_shrinks', 1.0, false),
  ('potato', 'starchy_veg', 'Potato', 'ciqual', '4023', 'Pomme de terre nouvelle, crue', 76.4, 1.9, 15.9, 0.3, 1.3, false, false, false, false, false, false, false, 'veg_shrinks', 1.0, false),
  ('sweet_potato', 'starchy_veg', 'Sweet potato', 'ciqual', '4101', 'Patate douce, crue', 86.3, 1.5, 18.3, 0.1, 2.9, false, false, false, false, false, false, false, 'veg_shrinks', 1.0, false),
  ('sweetcorn', 'starchy_veg', 'Sweetcorn', 'ciqual', '20066', 'Maïs doux, appertisé, égoutté', 106.0, 2.8, 18.4, 1.7, 3.1, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('biscuits', 'sugar_sweets', 'Biscuits', 'ciqual', '24001', 'Biscuit sec nature', 448.6, 6.8, 70.0, 15.1, 2.8, false, true, false, false, false, false, false, 'neutral', 1.0, true),
  ('dark_chocolate', 'sugar_sweets', 'Dark chocolate', 'ciqual', '31080', 'Chocolat noir fourré praliné, tablette', 558.5, 6.4, 52.4, 34.8, 5.1, false, true, false, false, true, false, true, 'neutral', 1.0, true),
  ('honey', 'sugar_sweets', 'Honey', 'ciqual', '31008', 'Miel', 329.0, 0.6, 81.7, 0.0, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, true),
  ('ice_cream', 'sugar_sweets', 'Ice cream', 'ciqual', '39526', 'Glace à l''eau', 85.7, 0.1, 20.8, 0.2, 0.2, false, false, false, false, false, false, false, 'neutral', 1.0, true),
  ('jam', 'sugar_sweets', 'Jam', 'ciqual', '31040', 'Confiture de lait', 308.0, 6.5, 58.0, 5.5, 0.6, false, false, true, false, false, false, false, 'neutral', 1.0, true),
  ('maple_syrup', 'sugar_sweets', 'Maple syrup', 'ciqual', '31034', 'Sirop d''érable', 269.1, 0.0, 67.1, 0.1, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, true),
  ('sugar', 'sugar_sweets', 'Sugar', 'ciqual', '31016', 'Sucre blanc', 399.2, 0.0, 99.8, 0.0, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, true),
  ('cola', 'sweetened_beverage', 'Cola', 'ciqual', '18018', 'Cola, sucré', 41.8, 0.1, 10.2, 0.1, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('orange_juice', 'sweetened_beverage', 'Orange juice', 'ciqual', '2013', 'Jus d''orange, maison', 42.6, 0.7, 9.4, 0.2, 0.2, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('soy_milk', 'tofu_tempeh', 'Soy drink', 'ciqual', '18900', 'Boisson au soja, nature, non enrichie, préemballée', 37.1, 3.3, 0.7, 2.1, 0.6, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('tempeh', 'tofu_tempeh', 'Tempeh', 'ciqual', '20917', 'Tempeh', 157.0, 16.1, 7.9, 4.7, 6.2, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('tofu', 'tofu_tempeh', 'Tofu', 'ciqual', '20912', 'Tofu fumé, préemballé', 164.0, 14.9, 2.9, 9.5, null, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('water', 'water', 'Water', 'ciqual', '18066', 'Eau du robinet', 0.0, 0.0, 0.0, 0.0, 0.0, false, false, false, false, false, false, false, 'neutral', 1.0, false),
  ('cod', 'white_fish', 'Cod', 'ciqual', '26043', 'Cabillaud, cru', 77.6, 18.1, 0.0, 0.6, null, false, false, false, true, false, true, false, 'fish_shrinks', 1.0, false),
  ('haddock', 'white_fish', 'Haddock', 'ciqual', '26122', 'Églefin, cru', 72.3, 17.3, 0.0, 0.3, 0.0, false, false, false, true, false, true, false, 'fish_shrinks', 1.0, false),
  ('hake', 'white_fish', 'Hake', 'ciqual', '26044', 'Merlu, cru', 82.6, 17.6, 0.0, 1.4, 0.0, false, false, false, true, false, true, false, 'fish_shrinks', 1.0, false),
  ('plaice', 'white_fish', 'Plaice', 'ciqual', '26055', 'Carrelet ou plie, cru', 88.6, 20.0, 0.0, 0.9, 0.0, false, false, true, true, false, true, false, 'fish_shrinks', 1.0, false),
  ('pollock', 'white_fish', 'Pollock', 'ciqual', '26134', 'Lieu noir, cru', 82.5, 18.8, 0.0, 0.8, 0.0, false, false, false, true, false, true, false, 'fish_shrinks', 1.0, false),
  ('sea_bass', 'white_fish', 'Sea bass', 'ciqual', '26001', 'Bar rayé ou bar d''Amérique, cru', 113.0, 20.3, 0.0, 3.6, 0.0, true, false, false, true, false, true, false, 'fish_shrinks', 1.0, false),
  ('tuna_fresh', 'white_fish', 'Tuna steak', 'ciqual', '26053', 'Thon, cru', 144.0, 24.0, 0.0, 5.4, 0.0, true, false, false, true, false, true, false, 'fish_shrinks', 1.0, false),
  ('tuna_tinned', 'white_fish', 'Tinned tuna', 'ciqual', '26039', 'Thon, au naturel, appertisé, égoutté', 111.0, 26.8, 0.0, 0.4, 0.0, false, false, false, false, false, true, false, 'neutral', 1.0, false),
  ('barley', 'whole_grain', 'Barley', 'ciqual', '9321', 'Orge perlée, crue', 346.0, 9.9, 68.6, 1.2, 9.1, false, true, false, false, true, false, false, 'grain_absorbs', 1.0, false),
  ('brown_rice', 'whole_grain', 'Brown rice', 'ciqual', '9102', 'Riz complet, cru', 350.0, 7.0, 71.4, 2.8, 5.0, false, false, false, false, true, false, true, 'grain_absorbs', 1.0, false),
  ('buckwheat', 'whole_grain', 'Buckwheat', 'ciqual', '9380', 'Sarrasin entier, cru', 356.0, 12.9, 64.6, 3.5, 7.0, false, true, false, false, true, false, true, 'grain_absorbs', 1.0, false),
  ('bulgur', 'whole_grain', 'Bulgur', 'ciqual', '9690', 'Boulgour de blé, cru', 351.0, 11.5, 66.8, 1.7, 9.6, false, true, false, false, true, false, false, 'grain_absorbs', 1.0, false),
  ('oats', 'whole_grain', 'Oats', 'ciqual', '9311', 'Flocon d''avoine', 367.0, 13.3, 57.9, 6.5, 10.2, false, true, false, false, true, false, true, 'neutral', 1.0, false),
  ('quinoa', 'whole_grain', 'Quinoa', 'ciqual', '9340', 'Quinoa, cru', 358.0, 13.2, 58.1, 6.1, 7.0, false, true, false, false, true, false, true, 'grain_absorbs', 1.0, false),
  ('rye_bread', 'whole_grain', 'Rye bread', 'ciqual', '7125', 'Pain de seigle, et froment', 260.0, 8.3, 51.5, 1.0, 4.5, false, false, false, false, false, false, true, 'neutral', 1.0, false),
  ('wholemeal_bread', 'whole_grain', 'Wholemeal bread', 'ciqual', '7111', 'Pain de mie, complet', 262.0, 8.5, 43.7, 4.1, 6.2, false, false, true, false, false, false, false, 'neutral', 1.0, false),
  ('wholewheat_pasta', 'whole_grain', 'Wholewheat pasta', 'ciqual', '9870', 'Pâtes sèches, au blé complet, crues', 353.0, 11.8, 67.6, 2.2, 6.1, false, true, false, false, true, false, false, 'grain_absorbs', 1.0, false)
on conflict (slug) do update set
  food_group_ref = excluded.food_group_ref,
  label = excluded.label,
  source = excluded.source,
  ciqual_code = excluded.ciqual_code,
  ciqual_name = excluded.ciqual_name,
  energy_kcal = excluded.energy_kcal,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  omega3_marine = excluded.omega3_marine,
  iron_source = excluded.iron_source,
  calcium_source = excluded.calcium_source,
  iodine_source = excluded.iodine_source,
  zinc_source = excluded.zinc_source,
  b12_source = excluded.b12_source,
  folate_source = excluded.folate_source,
  yield_class = excluded.yield_class,
  atwater_discount = excluded.atwater_discount,
  energy_dense = excluded.energy_dense;

insert into public.food_composition_aliases (alias, slug)
values
  ('abricots secs', 'dried_apricot'),
  ('agneau', 'lamb'),
  ('ail', 'garlic'),
  ('almond', 'almonds'),
  ('almonds', 'almonds'),
  ('amandes', 'almonds'),
  ('ananas', 'pineapple'),
  ('anchois', 'anchovy'),
  ('anchovies', 'anchovy'),
  ('anchovy', 'anchovy'),
  ('apple', 'apple'),
  ('apples', 'apple'),
  ('arugula', 'rocket'),
  ('asparagus', 'asparagus'),
  ('asperge', 'asparagus'),
  ('asperges', 'asparagus'),
  ('aubergine', 'aubergine'),
  ('avocado', 'avocado'),
  ('avocados', 'avocado'),
  ('avocat', 'avocado'),
  ('avoine', 'oats'),
  ('baby carrots', 'carrot'),
  ('baby potatoes', 'potato'),
  ('baby spinach', 'spinach'),
  ('bacon', 'bacon'),
  ('baguette', 'white_bread'),
  ('baked beans', 'baked_beans'),
  ('balsamic vinegar', 'vinegar'),
  ('banana', 'banana'),
  ('bananas', 'banana'),
  ('banane', 'banana'),
  ('bananes', 'banana'),
  ('bar', 'sea_bass'),
  ('barley', 'barley'),
  ('basil', 'herbs_basil'),
  ('basilic', 'herbs_basil'),
  ('basmati rice', 'white_rice'),
  ('beef chuck', 'beef_braising'),
  ('beef mince', 'beef_mince'),
  ('beef steak', 'beef_steak'),
  ('beef stock', 'stock_cube'),
  ('beer', 'beer'),
  ('beetroot', 'beetroot'),
  ('beets', 'beetroot'),
  ('bell pepper', 'bell_pepper'),
  ('bell peppers', 'bell_pepper'),
  ('berries', 'mixed_berries'),
  ('betterave', 'beetroot'),
  ('beurre', 'butter'),
  ('beurre clarifie', 'ghee'),
  ('beurre de cacahuete', 'peanut_butter'),
  ('biere', 'beer'),
  ('biscuit', 'biscuits'),
  ('biscuits', 'biscuits'),
  ('biscuits secs', 'biscuits'),
  ('black beans', 'black_beans'),
  ('black coffee', 'coffee'),
  ('black olives', 'olives'),
  ('black pepper', 'black_pepper'),
  ('black tea', 'tea'),
  ('blanc d''oeuf', 'egg_white'),
  ('blanc de dinde', 'turkey_breast'),
  ('blanc de poulet', 'chicken_breast'),
  ('blancs d''oeufs', 'egg_white'),
  ('ble noir', 'buckwheat'),
  ('blette', 'swiss_chard'),
  ('blettes', 'swiss_chard'),
  ('blueberries', 'blueberries'),
  ('blueberry', 'blueberries'),
  ('boeuf a braiser', 'beef_braising'),
  ('boiling water', 'water'),
  ('boisson au soja', 'soy_milk'),
  ('bok choy', 'pak_choi'),
  ('bouillon', 'stock_cube'),
  ('boulgour', 'bulgur'),
  ('braising beef', 'beef_braising'),
  ('bread', 'white_bread'),
  ('breakfast cereal', 'breakfast_cereal'),
  ('broad beans', 'broad_beans'),
  ('broccoli', 'broccoli'),
  ('brocoli', 'broccoli'),
  ('brocolis', 'broccoli'),
  ('broth', 'stock_cube'),
  ('brown bread', 'wholemeal_bread'),
  ('brown rice', 'brown_rice'),
  ('brown sugar', 'sugar'),
  ('brussels sprouts', 'brussels_sprouts'),
  ('buckwheat', 'buckwheat'),
  ('bulghur', 'bulgur'),
  ('bulgur', 'bulgur'),
  ('butter', 'butter'),
  ('butter beans', 'white_beans'),
  ('butternut squash', 'butternut_squash'),
  ('button mushrooms', 'mushroom'),
  ('cabbage', 'cabbage'),
  ('cabillaud', 'cod'),
  ('cacahuete', 'peanuts'),
  ('cacahuetes', 'peanuts'),
  ('cafe', 'coffee'),
  ('calamari', 'squid'),
  ('calmar', 'squid'),
  ('canned chickpeas', 'chickpeas_tinned'),
  ('canned tomatoes', 'tinned_tomatoes'),
  ('canned tuna', 'tuna_tinned'),
  ('cannelle', 'cinnamon'),
  ('cannellini beans', 'white_beans'),
  ('canola oil', 'rapeseed_oil'),
  ('cantaloupe', 'melon'),
  ('carotte', 'carrot'),
  ('carottes', 'carrot'),
  ('carrelet', 'plaice'),
  ('carrot', 'carrot'),
  ('carrots', 'carrot'),
  ('cashew nuts', 'cashews'),
  ('cashews', 'cashews'),
  ('caster sugar', 'sugar'),
  ('cauliflower', 'cauliflower'),
  ('cebette', 'spring_onion'),
  ('celeri', 'celery'),
  ('celeri branche', 'celery'),
  ('celery', 'celery'),
  ('cereales', 'breakfast_cereal'),
  ('champignon', 'mushroom'),
  ('champignons', 'mushroom'),
  ('chard', 'swiss_chard'),
  ('cheddar', 'cheddar'),
  ('cheddar cheese', 'cheddar'),
  ('cherry tomatoes', 'tomato'),
  ('chestnut mushrooms', 'mushroom'),
  ('chevre', 'goat_cheese'),
  ('chia', 'chia_seeds'),
  ('chia seeds', 'chia_seeds'),
  ('chick peas', 'chickpeas_tinned'),
  ('chicken', 'chicken_breast'),
  ('chicken breast', 'chicken_breast'),
  ('chicken breasts', 'chicken_breast'),
  ('chicken fillet', 'chicken_breast'),
  ('chicken legs', 'chicken_thigh'),
  ('chicken stock', 'stock_cube'),
  ('chicken thigh', 'chicken_thigh'),
  ('chicken thighs', 'chicken_thigh'),
  ('chickpea', 'chickpeas_tinned'),
  ('chickpeas', 'chickpeas_tinned'),
  ('chili', 'chilli'),
  ('chili powder', 'chilli_powder'),
  ('chilli', 'chilli'),
  ('chilli flakes', 'chilli_powder'),
  ('chilli powder', 'chilli_powder'),
  ('chillies', 'chilli'),
  ('chips', 'chips_fries'),
  ('chocolat noir', 'dark_chocolate'),
  ('chopped tomatoes', 'tinned_tomatoes'),
  ('chorizo', 'chorizo'),
  ('chou', 'cabbage'),
  ('chou chinois', 'pak_choi'),
  ('chou fleur', 'cauliflower'),
  ('chou frise', 'kale'),
  ('chou kale', 'kale'),
  ('chou rouge', 'red_cabbage'),
  ('chou vert', 'cabbage'),
  ('chou-fleur', 'cauliflower'),
  ('choux de bruxelles', 'brussels_sprouts'),
  ('cider vinegar', 'vinegar'),
  ('cilantro', 'herbs_coriander'),
  ('cinnamon', 'cinnamon'),
  ('citron', 'lemon'),
  ('citron vert', 'lime'),
  ('clementine', 'clementine'),
  ('clementines', 'clementine'),
  ('coconut milk', 'coconut_milk'),
  ('coconut oil', 'coconut_oil'),
  ('cod', 'cod'),
  ('cod fillet', 'cod'),
  ('coffee', 'coffee'),
  ('cola', 'cola'),
  ('cold water', 'water'),
  ('coley', 'pollock'),
  ('colin', 'hake'),
  ('concentre de tomate', 'tomato_puree'),
  ('concombre', 'cucumber'),
  ('confiture', 'jam'),
  ('cooked ham', 'ham'),
  ('cooked lentils', 'lentils_cooked'),
  ('cooked rice', 'cooked_rice'),
  ('cookies', 'biscuits'),
  ('coriander', 'herbs_coriander'),
  ('coriandre', 'herbs_coriander'),
  ('corn', 'sweetcorn'),
  ('cornflakes', 'breakfast_cereal'),
  ('cote de porc', 'pork_chop'),
  ('cotes de porc', 'pork_chop'),
  ('cottage cheese', 'cottage_cheese'),
  ('coulis de tomate', 'passata'),
  ('courge butternut', 'butternut_squash'),
  ('courgette', 'courgette'),
  ('courgettes', 'courgette'),
  ('couscous', 'couscous'),
  ('crab', 'crab'),
  ('crab meat', 'crab'),
  ('crabe', 'crab'),
  ('cream', 'single_cream'),
  ('cream cheese', 'cream_cheese'),
  ('creme fraiche', 'creme_fraiche'),
  ('creme glacee', 'ice_cream'),
  ('creme liquide', 'single_cream'),
  ('cresson', 'watercress'),
  ('crevette', 'prawns'),
  ('crevettes', 'prawns'),
  ('crisps', 'crisps'),
  ('crunchy oat cereal', 'granola'),
  ('cucumber', 'cucumber'),
  ('cuisse de poulet', 'chicken_thigh'),
  ('cuisses de poulet', 'chicken_thigh'),
  ('cumin', 'cumin'),
  ('curry', 'curry_paste'),
  ('curry paste', 'curry_paste'),
  ('curry powder', 'curry_paste'),
  ('dark chocolate', 'dark_chocolate'),
  ('dates', 'dates'),
  ('dattes', 'dates'),
  ('dijon mustard', 'mustard'),
  ('dinde hachee', 'turkey_mince'),
  ('double cream', 'single_cream'),
  ('dried apricots', 'dried_apricot'),
  ('dried chickpeas', 'chickpeas_dry'),
  ('dried lentils', 'lentils_dry'),
  ('duck', 'duck_breast'),
  ('duck breast', 'duck_breast'),
  ('eau', 'water'),
  ('edamame', 'edamame'),
  ('egg', 'whole_eggs'),
  ('egg white', 'egg_white'),
  ('egg whites', 'egg_white'),
  ('egg yolk', 'egg_yolk'),
  ('egg yolks', 'egg_yolk'),
  ('eggplant', 'aubergine'),
  ('eggs', 'whole_eggs'),
  ('eglefin', 'haddock'),
  ('encornet', 'squid'),
  ('epinard', 'spinach'),
  ('epinards', 'spinach'),
  ('escalope de dinde', 'turkey_breast'),
  ('escalope de poulet', 'chicken_breast'),
  ('extra virgin olive oil', 'olive_oil'),
  ('faisselle', 'fromage_blanc'),
  ('fava beans', 'broad_beans'),
  ('fennel', 'fennel'),
  ('fenouil', 'fennel'),
  ('feta', 'feta'),
  ('feta cheese', 'feta'),
  ('feves', 'broad_beans'),
  ('feves de soja', 'edamame'),
  ('filet de poulet', 'chicken_breast'),
  ('filet de saumon', 'salmon'),
  ('filet mignon de porc', 'pork_loin'),
  ('fine beans', 'green_beans'),
  ('firm tofu', 'tofu'),
  ('flageolets', 'white_beans'),
  ('flaked almonds', 'almonds'),
  ('flat-leaf parsley', 'herbs_parsley'),
  ('flaxseed', 'flaxseed'),
  ('flocons d''avoine', 'oats'),
  ('fraises', 'strawberries'),
  ('framboises', 'raspberries'),
  ('french beans', 'green_beans'),
  ('french dressing', 'vinaigrette'),
  ('french fries', 'chips_fries'),
  ('fresh ginger', 'ginger'),
  ('fresh tuna', 'tuna_fresh'),
  ('fries', 'chips_fries'),
  ('frites', 'chips_fries'),
  ('fromage a tartiner', 'cream_cheese'),
  ('fromage blanc', 'fromage_blanc'),
  ('fromage de chevre', 'goat_cheese'),
  ('frozen berries', 'mixed_berries'),
  ('frozen peas', 'green_peas'),
  ('frozen vegetables', 'peas_frozen'),
  ('fruit juice', 'orange_juice'),
  ('fruits a coque', 'mixed_nuts'),
  ('fruits rouges', 'mixed_berries'),
  ('fusilli', 'white_pasta'),
  ('gammon', 'ham'),
  ('garden peas', 'green_peas'),
  ('garlic', 'garlic'),
  ('garlic clove', 'garlic'),
  ('garlic cloves', 'garlic'),
  ('gem lettuce', 'lettuce'),
  ('ghee', 'ghee'),
  ('gigot d''agneau', 'lamb'),
  ('gingembre', 'ginger'),
  ('ginger', 'ginger'),
  ('glace', 'ice_cream'),
  ('goat cheese', 'goat_cheese'),
  ('goats cheese', 'goat_cheese'),
  ('gousse d''ail', 'garlic'),
  ('gousses d''ail', 'garlic'),
  ('graines de chia', 'chia_seeds'),
  ('graines de courge', 'pumpkin_seeds'),
  ('graines de lin', 'flaxseed'),
  ('graines de sesame', 'sesame_seeds'),
  ('graines de tournesol', 'sunflower_seeds'),
  ('granola', 'granola'),
  ('grapefruit', 'grapefruit'),
  ('grapes', 'grapes'),
  ('grated cheddar', 'cheddar'),
  ('grated parmesan', 'parmesan'),
  ('greek yoghurt', 'greek_yogurt'),
  ('greek yogurt', 'greek_yogurt'),
  ('green beans', 'green_beans'),
  ('green lentils', 'lentils_dry'),
  ('green olives', 'olives'),
  ('green tea', 'tea'),
  ('ground almonds', 'almonds'),
  ('ground beef', 'beef_mince'),
  ('ground cumin', 'cumin'),
  ('ground turkey', 'turkey_mince'),
  ('haddock', 'haddock'),
  ('hake', 'hake'),
  ('halloumi', 'halloumi'),
  ('ham', 'ham'),
  ('hareng', 'herring'),
  ('haricot blanc', 'white_beans'),
  ('haricot rouge', 'kidney_beans'),
  ('haricot vert', 'green_beans'),
  ('haricots a la sauce tomate', 'baked_beans'),
  ('haricots blancs', 'white_beans'),
  ('haricots noirs', 'black_beans'),
  ('haricots rouges', 'kidney_beans'),
  ('haricots verts', 'green_beans'),
  ('hazelnuts', 'hazelnuts'),
  ('herring', 'herring'),
  ('honey', 'honey'),
  ('hoummous', 'hummus'),
  ('houmous', 'hummus'),
  ('huile d''olive', 'olive_oil'),
  ('huile de coco', 'coconut_oil'),
  ('huile de colza', 'rapeseed_oil'),
  ('huile de sesame', 'sesame_oil'),
  ('huile de tournesol', 'sunflower_oil'),
  ('huile vegetale', 'rapeseed_oil'),
  ('hummus', 'hummus'),
  ('ice cream', 'ice_cream'),
  ('jam', 'jam'),
  ('jambon', 'ham'),
  ('jambon blanc', 'ham'),
  ('jasmine rice', 'white_rice'),
  ('jaune d''oeuf', 'egg_yolk'),
  ('jumbo oats', 'oats'),
  ('jus d''orange', 'orange_juice'),
  ('jus de citron', 'lemon'),
  ('jus de fruit', 'orange_juice'),
  ('kale', 'kale'),
  ('kefir', 'kefir'),
  ('ketchup', 'ketchup'),
  ('kidney beans', 'kidney_beans'),
  ('king prawns', 'prawns'),
  ('kiwi', 'kiwi'),
  ('kiwis', 'kiwi'),
  ('lait', 'milk_semi'),
  ('lait de coco', 'coconut_milk'),
  ('lait de soja', 'soy_milk'),
  ('lait demi-ecreme', 'milk_semi'),
  ('laitue', 'lettuce'),
  ('lamb', 'lamb'),
  ('lamb chop', 'lamb'),
  ('lamb chops', 'lamb'),
  ('lamb leg', 'lamb'),
  ('lardons', 'bacon'),
  ('large egg', 'whole_eggs'),
  ('large eggs', 'whole_eggs'),
  ('large potato', 'potato'),
  ('lean beef mince', 'beef_mince'),
  ('lean turkey mince', 'turkey_mince'),
  ('leek', 'leek'),
  ('leeks', 'leek'),
  ('leftover rice', 'cooked_rice'),
  ('legumes surgeles', 'peas_frozen'),
  ('lemon', 'lemon'),
  ('lemon juice', 'lemon'),
  ('lemon zest', 'lemon'),
  ('lemons', 'lemon'),
  ('lentil', 'lentils_dry'),
  ('lentille', 'lentils_dry'),
  ('lentilles', 'lentils_dry'),
  ('lentilles corail', 'lentils_dry'),
  ('lentilles cuites', 'lentils_cooked'),
  ('lentilles vertes', 'lentils_dry'),
  ('lentils', 'lentils_dry'),
  ('lettuce', 'lettuce'),
  ('lieu noir', 'pollock'),
  ('light mayonnaise', 'mayonnaise'),
  ('lime', 'lime'),
  ('lime juice', 'lime'),
  ('limes', 'lime'),
  ('linseed', 'flaxseed'),
  ('long grain rice', 'white_rice'),
  ('loup de mer', 'sea_bass'),
  ('macaroni', 'white_pasta'),
  ('mackerel', 'mackerel'),
  ('magret de canard', 'duck_breast'),
  ('mais doux', 'sweetcorn'),
  ('mandarin', 'clementine'),
  ('mango', 'mango'),
  ('mangue', 'mango'),
  ('maple syrup', 'maple_syrup'),
  ('maquereau', 'mackerel'),
  ('mayo', 'mayonnaise'),
  ('mayonnaise', 'mayonnaise'),
  ('medium egg', 'whole_eggs'),
  ('medjool dates', 'dates'),
  ('melon', 'melon'),
  ('menthe', 'herbs_mint'),
  ('merlu', 'hake'),
  ('mesclun', 'lettuce'),
  ('miel', 'honey'),
  ('milk', 'milk_semi'),
  ('minced beef', 'beef_mince'),
  ('minced turkey', 'turkey_mince'),
  ('mint', 'herbs_mint'),
  ('mixed berries', 'mixed_berries'),
  ('mixed leaves', 'lettuce'),
  ('mixed nuts', 'mixed_nuts'),
  ('mixed salad leaves', 'lettuce'),
  ('mixed vegetables', 'peas_frozen'),
  ('morue', 'cod'),
  ('moule', 'mussels'),
  ('moules', 'mussels'),
  ('moutarde', 'mustard'),
  ('mozzarella', 'mozzarella'),
  ('muesli', 'granola'),
  ('mushroom', 'mushroom'),
  ('mushrooms', 'mushroom'),
  ('mussel', 'mussels'),
  ('mussels', 'mussels'),
  ('mustard', 'mustard'),
  ('myrtilles', 'blueberries'),
  ('natural yogurt', 'plain_yogurt'),
  ('nectarine', 'peach'),
  ('new potatoes', 'potato'),
  ('noisettes', 'hazelnuts'),
  ('noix', 'walnuts'),
  ('noix de cajou', 'cashews'),
  ('noix de saint jacques', 'scallops'),
  ('noodles', 'noodles'),
  ('nouilles', 'noodles'),
  ('nuts', 'mixed_nuts'),
  ('oats', 'oats'),
  ('oeuf', 'whole_eggs'),
  ('oeufs', 'whole_eggs'),
  ('oignon', 'onion'),
  ('oignon nouveau', 'spring_onion'),
  ('oignon rouge', 'onion'),
  ('oignons', 'onion'),
  ('oil', 'olive_oil'),
  ('olive', 'olives'),
  ('olive oil', 'olive_oil'),
  ('olives', 'olives'),
  ('onion', 'onion'),
  ('onions', 'onion'),
  ('orange', 'orange'),
  ('orange juice', 'orange_juice'),
  ('oranges', 'orange'),
  ('orge', 'barley'),
  ('pain', 'white_bread'),
  ('pain complet', 'wholemeal_bread'),
  ('pain de mie', 'white_bread'),
  ('pain de seigle', 'rye_bread'),
  ('pak choi', 'pak_choi'),
  ('paleron', 'beef_braising'),
  ('pamplemousse', 'grapefruit'),
  ('panais', 'parsnip'),
  ('pancetta', 'bacon'),
  ('paprika', 'paprika'),
  ('parmesan', 'parmesan'),
  ('parmigiano', 'parmesan'),
  ('parsley', 'herbs_parsley'),
  ('parsnip', 'parsnip'),
  ('parsnips', 'parsnip'),
  ('passata', 'passata'),
  ('pasta', 'white_pasta'),
  ('pasteque', 'melon'),
  ('patate douce', 'sweet_potato'),
  ('pate de curry', 'curry_paste'),
  ('pates', 'white_pasta'),
  ('pates completes', 'wholewheat_pasta'),
  ('pave de saumon', 'salmon'),
  ('peach', 'peach'),
  ('peaches', 'peach'),
  ('peanut', 'peanuts'),
  ('peanut butter', 'peanut_butter'),
  ('peanuts', 'peanuts'),
  ('pear', 'pear'),
  ('pearl barley', 'barley'),
  ('pears', 'pear'),
  ('peas', 'green_peas'),
  ('peche', 'peach'),
  ('peches', 'peach'),
  ('penne', 'white_pasta'),
  ('peppers', 'bell_pepper'),
  ('persil', 'herbs_parsley'),
  ('pesto', 'pesto'),
  ('petit pois', 'green_peas'),
  ('petits pois', 'green_peas'),
  ('piment', 'chilli'),
  ('piment en poudre', 'chilli_powder'),
  ('pineapple', 'pineapple'),
  ('pita bread', 'white_bread'),
  ('pitta', 'white_bread'),
  ('plaice', 'plaice'),
  ('plain yoghurt', 'plain_yogurt'),
  ('plain yogurt', 'plain_yogurt'),
  ('plie', 'plaice'),
  ('plum tomatoes', 'tomato'),
  ('poire', 'pear'),
  ('poireau', 'leek'),
  ('poireaux', 'leek'),
  ('pois chiche', 'chickpeas_tinned'),
  ('pois chiches', 'chickpeas_tinned'),
  ('pois chiches secs', 'chickpeas_dry'),
  ('poivre', 'black_pepper'),
  ('poivre noir', 'black_pepper'),
  ('poivron', 'bell_pepper'),
  ('poivrons', 'bell_pepper'),
  ('polenta', 'polenta'),
  ('pollock', 'pollock'),
  ('pomme', 'apple'),
  ('pomme de terre', 'potato'),
  ('pommes', 'apple'),
  ('pommes de terre', 'potato'),
  ('pork chop', 'pork_chop'),
  ('pork chops', 'pork_chop'),
  ('pork fillet', 'pork_loin'),
  ('pork loin', 'pork_loin'),
  ('pork sausage', 'sausage'),
  ('pork tenderloin', 'pork_loin'),
  ('porridge oats', 'oats'),
  ('potato', 'potato'),
  ('potato chips', 'crisps'),
  ('potatoes', 'potato'),
  ('potiron', 'butternut_squash'),
  ('pousses d''epinard', 'spinach'),
  ('prawn', 'prawns'),
  ('prawns', 'prawns'),
  ('pumpkin', 'butternut_squash'),
  ('pumpkin seeds', 'pumpkin_seeds'),
  ('puree de sesame', 'tahini'),
  ('puy lentils', 'lentils_dry'),
  ('quark', 'fromage_blanc'),
  ('quinoa', 'quinoa'),
  ('radis', 'radish'),
  ('radish', 'radish'),
  ('radishes', 'radish'),
  ('rainbow trout', 'trout'),
  ('raisin frais', 'grapes'),
  ('raisins', 'raisins'),
  ('raisins secs', 'raisins'),
  ('rapeseed oil', 'rapeseed_oil'),
  ('raspberries', 'raspberries'),
  ('raspberry', 'raspberries'),
  ('red cabbage', 'red_cabbage'),
  ('red chilli', 'chilli'),
  ('red kidney beans', 'kidney_beans'),
  ('red lentils', 'lentils_dry'),
  ('red onion', 'onion'),
  ('red pepper', 'bell_pepper'),
  ('red peppers', 'bell_pepper'),
  ('red wine', 'wine'),
  ('rice', 'white_rice'),
  ('rice noodles', 'noodles'),
  ('riz', 'white_rice'),
  ('riz basmati', 'white_rice'),
  ('riz blanc', 'white_rice'),
  ('riz brun', 'brown_rice'),
  ('riz complet', 'brown_rice'),
  ('riz cuit', 'cooked_rice'),
  ('rocket', 'rocket'),
  ('rolled oats', 'oats'),
  ('romaine', 'lettuce'),
  ('romarin', 'herbs_thyme'),
  ('roquette', 'rocket'),
  ('rosemary', 'herbs_thyme'),
  ('rump steak', 'beef_steak'),
  ('rye bread', 'rye_bread'),
  ('saint jacques', 'scallops'),
  ('salad dressing', 'vinaigrette'),
  ('salad leaves', 'lettuce'),
  ('salade', 'lettuce'),
  ('salade verte', 'lettuce'),
  ('salmon', 'salmon'),
  ('salmon fillet', 'salmon'),
  ('salmon fillets', 'salmon'),
  ('salsa', 'salsa'),
  ('salt', 'salt'),
  ('salt and pepper', 'salt'),
  ('sardine', 'sardines'),
  ('sardines', 'sardines'),
  ('sardines a l''huile', 'sardines'),
  ('sarrasin', 'buckwheat'),
  ('satsuma', 'clementine'),
  ('sauce soja', 'soy_sauce'),
  ('saucisse', 'sausage'),
  ('saucisses', 'sausage'),
  ('saumon', 'salmon'),
  ('saumon fume', 'smoked_salmon'),
  ('sausage', 'sausage'),
  ('sausages', 'sausage'),
  ('savoy cabbage', 'cabbage'),
  ('scallions', 'spring_onion'),
  ('scallop', 'scallops'),
  ('scallops', 'scallops'),
  ('sea bass', 'sea_bass'),
  ('sea salt', 'salt'),
  ('seabass', 'sea_bass'),
  ('sel', 'salt'),
  ('semi-skimmed milk', 'milk_semi'),
  ('semoule', 'couscous'),
  ('semoule de ble', 'couscous'),
  ('sesame oil', 'sesame_oil'),
  ('sesame seeds', 'sesame_seeds'),
  ('shrimp', 'prawns'),
  ('shrimps', 'prawns'),
  ('silken tofu', 'tofu'),
  ('single cream', 'single_cream'),
  ('sirloin', 'beef_steak'),
  ('sirop d''erable', 'maple_syrup'),
  ('skyr', 'skyr'),
  ('smoked paprika', 'paprika'),
  ('smoked salmon', 'smoked_salmon'),
  ('smoked tofu', 'tofu'),
  ('soft drink', 'cola'),
  ('sour cream', 'creme_fraiche'),
  ('soured cream', 'creme_fraiche'),
  ('soy beans', 'edamame'),
  ('soy drink', 'soy_milk'),
  ('soy milk', 'soy_milk'),
  ('soy sauce', 'soy_sauce'),
  ('soya beans', 'edamame'),
  ('soya milk', 'soy_milk'),
  ('soya sauce', 'soy_sauce'),
  ('spaghetti', 'white_pasta'),
  ('spinach', 'spinach'),
  ('spring onion', 'spring_onion'),
  ('spring onions', 'spring_onion'),
  ('sprouts', 'brussels_sprouts'),
  ('squash', 'butternut_squash'),
  ('squid', 'squid'),
  ('steak', 'beef_steak'),
  ('steak de boeuf', 'beef_steak'),
  ('steak hache', 'beef_mince'),
  ('stewing beef', 'beef_braising'),
  ('stir-fry vegetables', 'peas_frozen'),
  ('stock', 'stock_cube'),
  ('stock cube', 'stock_cube'),
  ('strawberries', 'strawberries'),
  ('strawberry', 'strawberries'),
  ('streaky bacon', 'bacon'),
  ('sucre', 'sugar'),
  ('sugar', 'sugar'),
  ('sultanas', 'raisins'),
  ('summer fruits', 'mixed_berries'),
  ('sunflower oil', 'sunflower_oil'),
  ('sunflower seeds', 'sunflower_seeds'),
  ('sweet potato', 'sweet_potato'),
  ('sweet potatoes', 'sweet_potato'),
  ('sweetcorn', 'sweetcorn'),
  ('swiss chard', 'swiss_chard'),
  ('tagliatelle', 'white_pasta'),
  ('tahin', 'tahini'),
  ('tahini', 'tahini'),
  ('tamari', 'soy_sauce'),
  ('tea', 'tea'),
  ('tempeh', 'tempeh'),
  ('tenderstem broccoli', 'broccoli'),
  ('the', 'tea'),
  ('the vert', 'tea'),
  ('thon', 'tuna_tinned'),
  ('thon au naturel', 'tuna_tinned'),
  ('thon en boite', 'tuna_tinned'),
  ('thon frais', 'tuna_fresh'),
  ('thym', 'herbs_thyme'),
  ('thyme', 'herbs_thyme'),
  ('tinned chickpeas', 'chickpeas_tinned'),
  ('tinned lentils', 'lentils_cooked'),
  ('tinned mackerel', 'mackerel'),
  ('tinned sardines', 'sardines'),
  ('tinned sweetcorn', 'sweetcorn'),
  ('tinned tomatoes', 'tinned_tomatoes'),
  ('tinned tuna', 'tuna_tinned'),
  ('toast', 'white_bread'),
  ('toasted sesame oil', 'sesame_oil'),
  ('tofu', 'tofu'),
  ('tofu ferme', 'tofu'),
  ('tofu fume', 'tofu'),
  ('tomate', 'tomato'),
  ('tomates', 'tomato'),
  ('tomates cerises', 'tomato'),
  ('tomates concassees', 'tinned_tomatoes'),
  ('tomates pelees', 'tinned_tomatoes'),
  ('tomato', 'tomato'),
  ('tomato passata', 'passata'),
  ('tomato paste', 'tomato_puree'),
  ('tomato puree', 'tomato_puree'),
  ('tomato salsa', 'salsa'),
  ('tomatoes', 'tomato'),
  ('tortilla', 'white_bread'),
  ('trout', 'trout'),
  ('truite', 'trout'),
  ('tuna', 'tuna_tinned'),
  ('tuna steak', 'tuna_fresh'),
  ('turkey', 'turkey_breast'),
  ('turkey breast', 'turkey_breast'),
  ('turkey escalope', 'turkey_breast'),
  ('turkey mince', 'turkey_mince'),
  ('udon', 'noodles'),
  ('unsalted butter', 'butter'),
  ('vegetable oil', 'rapeseed_oil'),
  ('vegetable stock', 'stock_cube'),
  ('viande hachee', 'beef_mince'),
  ('vin', 'wine'),
  ('vinaigre', 'vinegar'),
  ('vinaigre balsamique', 'vinegar'),
  ('vinaigrette', 'vinaigrette'),
  ('vine tomatoes', 'tomato'),
  ('vinegar', 'vinegar'),
  ('walnut', 'walnuts'),
  ('walnuts', 'walnuts'),
  ('water', 'water'),
  ('watercress', 'watercress'),
  ('watermelon', 'melon'),
  ('white beans', 'white_beans'),
  ('white bread', 'white_bread'),
  ('white cabbage', 'cabbage'),
  ('white onion', 'onion'),
  ('white rice', 'white_rice'),
  ('white wine', 'wine'),
  ('whole eggs', 'whole_eggs'),
  ('whole milk', 'milk_semi'),
  ('wholegrain bread', 'wholemeal_bread'),
  ('wholegrain mustard', 'mustard'),
  ('wholegrain rice', 'brown_rice'),
  ('wholegrain wrap', 'wholemeal_bread'),
  ('wholemeal bread', 'wholemeal_bread'),
  ('wholemeal pasta', 'wholewheat_pasta'),
  ('wholemeal toast', 'wholemeal_bread'),
  ('wholemeal wrap', 'wholemeal_bread'),
  ('wholewheat pasta', 'wholewheat_pasta'),
  ('wine', 'wine'),
  ('wrap', 'white_bread'),
  ('yaourt', 'plain_yogurt'),
  ('yaourt a la grecque', 'greek_yogurt'),
  ('yaourt grec', 'greek_yogurt'),
  ('yaourt nature', 'plain_yogurt'),
  ('yellow pepper', 'bell_pepper'),
  ('yoghurt', 'plain_yogurt'),
  ('yogurt', 'plain_yogurt'),
  ('zucchini', 'courgette')
on conflict (alias) do update set slug = excluded.slug;
