# FF-038 — LE CATALOGUE CURÉ.
#
# Chaque ligne est une DÉCISION: quel aliment on veut dans le référentiel, à
# quel groupe des trente il appartient, comment il se comporte à la cuisson, et
# sous quels noms le générateur l'écrit réellement.
#
# La colonne `ciqual` est un motif cherché dans `alim_nom_fr`. Elle ne décide de
# rien toute seule: le script imprime le nom retenu, et un appariement douteux
# est corrigé ici, jamais accepté en silence.
#
# yield_class — le rendement cru→cuit. Les FACTEURS vivent dans le module TS
# (constantes nommées), pas ici: la base porte la classe, le code porte le
# nombre.
#   neutral        1.00  rien n'absorbe ni ne perd (huiles, fruits, laitages…)
#   grain_absorbs  2.60  riz, pâtes, semoule, quinoa — poids cuit / poids cru
#   legume_absorbs 2.40  légumineuses SÈCHES (une conserve est déjà hydratée)
#   meat_shrinks   0.70  viandes et volailles
#   fish_shrinks   0.80  poissons et fruits de mer
#   veg_shrinks    0.90  légumes cuits
#
# energy_dense — la classe qui déclenche l'ABSTENTION du verdict (FF-039 R6):
# matières grasses, fruits à coque, sucres. Un seul de ces termes non résolu
# suffit à rendre un repas non calculable, parce qu'il déplace l'énergie de
# plusieurs dizaines de pour cent.

# slug, group, label_en, ciqual_pattern, yield_class, energy_dense, aliases
CATALOGUE = [
    # ── VOLAILLE ────────────────────────────────────────────────────────────
    ("chicken_breast", "poultry", "Chicken breast", r"^Poulet, filet, sans peau, cru", "meat_shrinks", 0,
     ["chicken breast", "chicken breasts", "chicken fillet", "blanc de poulet", "filet de poulet", "escalope de poulet", "chicken"]),
    ("chicken_thigh", "poultry", "Chicken thigh", r"^Poulet, cuisse, viande, cru", "meat_shrinks", 0,
     ["chicken thigh", "chicken thighs", "cuisse de poulet", "cuisses de poulet", "chicken legs"]),
    ("turkey_breast", "lean_protein", "Turkey breast", r"^Dinde, (escalope|blanc).*cru", "meat_shrinks", 0,
     ["turkey breast", "turkey escalope", "blanc de dinde", "escalope de dinde", "turkey"]),
    ("turkey_mince", "poultry", "Turkey mince", r"^Dinde, viande.*cru", "meat_shrinks", 0,
     ["turkey mince", "minced turkey", "lean turkey mince", "ground turkey", "dinde hachee"]),
    ("duck_breast", "poultry", "Duck breast", r"^Canard, magret.*cru", "meat_shrinks", 0,
     ["duck breast", "magret de canard", "duck"]),

    # ── VIANDES ROUGES ──────────────────────────────────────────────────────
    ("beef_steak", "red_meat", "Beef steak", r"^B(oe|œ)uf, steak.*cru", "meat_shrinks", 0,
     ["beef steak", "steak", "rump steak", "sirloin", "steak de boeuf"]),
    ("beef_mince", "red_meat", "Beef mince (5%)", r"^B(oe|œ)uf.*hach.*5 ?%.*cru", "meat_shrinks", 0,
     ["beef mince", "minced beef", "lean beef mince", "ground beef", "steak hache", "viande hachee"]),
    ("beef_braising", "red_meat", "Braising beef", r"^B(oe|œ)uf, (paleron|bourguignon).*cru", "meat_shrinks", 0,
     ["braising beef", "stewing beef", "beef chuck", "paleron", "boeuf a braiser"]),
    ("lamb", "red_meat", "Lamb", r"^Agneau, (gigot|c(o|ô)telette).*cru", "meat_shrinks", 0,
     ["lamb", "lamb leg", "lamb chop", "lamb chops", "agneau", "gigot d'agneau"]),
    ("pork_chop", "red_meat", "Pork chop", r"^Porc, c(o|ô)te.*cru", "meat_shrinks", 0,
     ["pork chop", "pork chops", "cote de porc", "cotes de porc"]),
    ("pork_loin", "lean_protein", "Pork loin", r"^Porc, filet.*cru", "meat_shrinks", 0,
     ["pork loin", "pork tenderloin", "pork fillet", "filet mignon de porc"]),
    ("bacon", "red_meat", "Bacon", r"^(Bacon|Lardon).*cru", "meat_shrinks", 0,
     ["bacon", "streaky bacon", "lardons", "pancetta"]),
    ("ham", "lean_protein", "Ham", r"^Jambon (blanc|cuit)", "neutral", 0,
     ["ham", "cooked ham", "gammon", "jambon", "jambon blanc"]),
    ("sausage", "red_meat", "Sausage", r"^Saucisse de (Toulouse|porc).*cru", "meat_shrinks", 0,
     ["sausage", "sausages", "pork sausage", "saucisse", "saucisses"]),
    ("chorizo", "red_meat", "Chorizo", r"^Chorizo", "neutral", 0,
     ["chorizo"]),

    # ── POISSONS GRAS ───────────────────────────────────────────────────────
    ("salmon", "fatty_fish", "Salmon", r"^Saumon, cru", "fish_shrinks", 0,
     ["salmon", "salmon fillet", "salmon fillets", "saumon", "filet de saumon", "pave de saumon"]),
    ("smoked_salmon", "fatty_fish", "Smoked salmon", r"^Saumon fum", "neutral", 0,
     ["smoked salmon", "saumon fume"]),
    ("mackerel", "fatty_fish", "Mackerel", r"^Maquereau.*cru", "fish_shrinks", 0,
     ["mackerel", "maquereau", "tinned mackerel"]),
    ("sardines", "fatty_fish", "Sardines", r"^Sardine.*(l'huile|huile de)", "neutral", 0,
     ["sardines", "sardine", "tinned sardines", "sardines a l'huile"]),
    ("trout", "fatty_fish", "Trout", r"^Truite.*cru", "fish_shrinks", 0,
     ["trout", "truite", "rainbow trout"]),
    ("herring", "fatty_fish", "Herring", r"^Hareng.*cru", "fish_shrinks", 0,
     ["herring", "hareng"]),
    ("anchovy", "fatty_fish", "Anchovies", r"^Anchois.*(l'huile|huile)", "neutral", 0,
     ["anchovies", "anchovy", "anchois"]),

    # ── POISSONS BLANCS ─────────────────────────────────────────────────────
    ("cod", "white_fish", "Cod", r"^Cabillaud.*cru", "fish_shrinks", 0,
     ["cod", "cod fillet", "cabillaud", "morue"]),
    ("haddock", "white_fish", "Haddock", r"^(Eglefin|Églefin|Haddock).*cru", "fish_shrinks", 0,
     ["haddock", "eglefin"]),
    ("sea_bass", "white_fish", "Sea bass", r"^Bar.*cru", "fish_shrinks", 0,
     ["sea bass", "seabass", "bar", "loup de mer"]),
    ("hake", "white_fish", "Hake", r"^Merlu.*cru", "fish_shrinks", 0,
     ["hake", "merlu", "colin"]),
    ("pollock", "white_fish", "Pollock", r"^Lieu noir.*cru", "fish_shrinks", 0,
     ["pollock", "lieu noir", "coley"]),
    ("plaice", "white_fish", "Plaice", r"^(Plie|Carrelet).*cru", "fish_shrinks", 0,
     ["plaice", "plie", "carrelet"]),
    ("tuna_tinned", "white_fish", "Tinned tuna", r"^Thon.*(au naturel|naturel)", "neutral", 0,
     ["tinned tuna", "canned tuna", "tuna", "thon", "thon en boite", "thon au naturel"]),
    ("tuna_fresh", "white_fish", "Tuna steak", r"^Thon.*cru", "fish_shrinks", 0,
     ["tuna steak", "fresh tuna", "thon frais"]),

    # ── FRUITS DE MER ───────────────────────────────────────────────────────
    ("prawns", "shellfish", "Prawns", r"^Crevette.*cuite", "neutral", 0,
     ["prawns", "prawn", "king prawns", "shrimp", "shrimps", "crevette", "crevettes"]),
    ("mussels", "shellfish", "Mussels", r"^Moule.*cuite", "neutral", 0,
     ["mussels", "mussel", "moule", "moules"]),
    ("squid", "shellfish", "Squid", r"^(Calmar|Calamar|Encornet).*cru", "fish_shrinks", 0,
     ["squid", "calamari", "calmar", "encornet"]),
    ("scallops", "shellfish", "Scallops", r"^(Coquille Saint-Jacques|P(e|é)toncle).*cru", "fish_shrinks", 0,
     ["scallops", "scallop", "saint jacques", "noix de saint jacques"]),
    ("crab", "shellfish", "Crab", r"^Crabe.*cuit", "neutral", 0,
     ["crab", "crabe", "crab meat"]),

    # ── ŒUFS ────────────────────────────────────────────────────────────────
    ("whole_eggs", "eggs", "Eggs", r"^(Oe|Œ)uf, cru", "neutral", 0,
     ["egg", "eggs", "whole eggs", "oeuf", "oeufs", "large egg", "large eggs", "medium egg"]),
    ("egg_white", "eggs", "Egg white", r"^(Oe|Œ)uf, blanc \(blanc d'(oe|œ)uf\), cru", "neutral", 0,
     ["egg white", "egg whites", "blanc d'oeuf", "blancs d'oeufs"]),
    ("egg_yolk", "eggs", "Egg yolk", r"^(Oe|Œ)uf, jaune \(jaune d'(oe|œ)uf\), cru", "neutral", 1,
     ["egg yolk", "egg yolks", "jaune d'oeuf"]),

    # ── LÉGUMINEUSES ────────────────────────────────────────────────────────
    ("lentils_dry", "legumes", "Lentils (dry)", r"^Lentille, s(e|è)che", "legume_absorbs", 0,
     ["dried lentils", "lentils", "lentil", "green lentils", "puy lentils", "red lentils", "lentille", "lentilles", "lentilles vertes", "lentilles corail"]),
    ("lentils_cooked", "legumes", "Lentils (cooked)", r"^Lentille, bouillie", "neutral", 0,
     ["cooked lentils", "tinned lentils", "lentilles cuites"]),
    ("chickpeas_dry", "legumes", "Chickpeas (dry)", r"^Pois chiche, sec", "legume_absorbs", 0,
     ["dried chickpeas", "pois chiches secs"]),
    ("chickpeas_tinned", "legumes", "Chickpeas (tinned)", r"^Pois chiche, appertis", "neutral", 0,
     ["chickpeas", "chickpea", "chick peas", "tinned chickpeas", "canned chickpeas", "pois chiche", "pois chiches"]),
    ("kidney_beans", "legumes", "Kidney beans", r"^Haricot rouge, appertis", "neutral", 0,
     ["kidney beans", "red kidney beans", "haricots rouges", "haricot rouge"]),
    ("black_beans", "legumes", "Black beans", r"^Haricot noir.*(cuit|conserve|cru)", "neutral", 0,
     ["black beans", "haricots noirs"]),
    ("white_beans", "legumes", "White beans", r"^Haricot blanc, appertis", "neutral", 0,
     ["white beans", "cannellini beans", "butter beans", "haricots blancs", "haricot blanc", "flageolets"]),
    ("baked_beans", "legumes", "Baked beans", r"^Haricot blanc.*sauce tomate", "neutral", 0,
     ["baked beans", "haricots a la sauce tomate"]),
    ("green_peas", "legumes", "Peas", r"^Petits pois, cuits", "neutral", 0,
     ["peas", "garden peas", "frozen peas", "petits pois", "petit pois"]),
    ("edamame", "legumes", "Edamame", r"^Soja, graine.*cuite", "neutral", 0,
     ["edamame", "soy beans", "soya beans", "feves de soja"]),
    ("broad_beans", "legumes", "Broad beans", r"^F(e|è)ve.*cuite", "neutral", 0,
     ["broad beans", "fava beans", "feves"]),
    ("hummus", "legumes", "Hummus", r"^Houmous", "neutral", 0,
     ["hummus", "houmous", "hoummous"]),

    # ── SOJA ────────────────────────────────────────────────────────────────
    ("tofu", "tofu_tempeh", "Tofu", r"^Tofu", "neutral", 0,
     ["tofu", "firm tofu", "silken tofu", "smoked tofu", "tofu ferme", "tofu fume"]),
    ("tempeh", "tofu_tempeh", "Tempeh", r"^Temp(e|é)", "neutral", 0,
     ["tempeh"]),
    ("soy_milk", "tofu_tempeh", "Soy drink", r"^Boisson au soja", "neutral", 0,
     ["soy milk", "soya milk", "soy drink", "lait de soja", "boisson au soja"]),

    # ── PRODUITS LAITIERS ───────────────────────────────────────────────────
    ("greek_yogurt", "dairy_yogurt", "Greek yogurt", r"^Yaourt.*(grec|(a|à) la grecque)", "neutral", 0,
     ["greek yogurt", "greek yoghurt", "yaourt grec", "yaourt a la grecque"]),
    ("plain_yogurt", "dairy_yogurt", "Plain yogurt", r"^Yaourt (nature|au lait entier, nature)", "neutral", 0,
     ["plain yogurt", "plain yoghurt", "natural yogurt", "yogurt", "yoghurt", "yaourt", "yaourt nature"]),
    ("skyr", "dairy_yogurt", "Skyr", r"^Skyr", "neutral", 0,
     ["skyr"]),
    ("fromage_blanc", "dairy_yogurt", "Fromage blanc", r"^Fromage blanc nature, 3% MG", "neutral", 0,
     ["fromage blanc", "quark", "faisselle"]),
    ("cottage_cheese", "dairy_yogurt", "Cottage cheese", r"^Cottage cheese", "neutral", 0,
     ["cottage cheese"]),
    ("kefir", "dairy_yogurt", "Kefir", r"^K(e|é)fir", "neutral", 0,
     ["kefir"]),
    ("milk_semi", "dairy_yogurt", "Semi-skimmed milk", r"^Lait, demi-(e|é)cr(e|é)m(e|é), UHT", "neutral", 0,
     ["milk", "semi-skimmed milk", "whole milk", "lait", "lait demi-ecreme"]),
    ("cheddar", "dairy_cheese", "Cheddar", r"^Cheddar", "neutral", 0,
     ["cheddar", "cheddar cheese", "grated cheddar"]),
    ("parmesan", "dairy_cheese", "Parmesan", r"^Parmesan", "neutral", 0,
     ["parmesan", "parmigiano", "grated parmesan"]),
    ("feta", "dairy_cheese", "Feta", r"^F(e|é)ta", "neutral", 0,
     ["feta", "feta cheese"]),
    ("mozzarella", "dairy_cheese", "Mozzarella", r"^Mozzarella", "neutral", 0,
     ["mozzarella"]),
    ("goat_cheese", "dairy_cheese", "Goat cheese", r"^(Ch(e|è)vre|Fromage de ch(e|è)vre)", "neutral", 0,
     ["goat cheese", "goats cheese", "fromage de chevre", "chevre"]),
    ("halloumi", "dairy_cheese", "Halloumi", r"^Hallo?umi", "neutral", 0,
     ["halloumi"]),
    ("cream_cheese", "dairy_cheese", "Cream cheese", r"^Fromage (a|à) tartiner", "neutral", 1,
     ["cream cheese", "fromage a tartiner"]),
    ("creme_fraiche", "other_added_fat", "Crème fraîche", r"^Cr(e|è)me fra(i|î)che.*30", "neutral", 1,
     ["creme fraiche", "sour cream", "soured cream"]),
    ("single_cream", "other_added_fat", "Cream", r"^Cr(e|è)me.*(15|liquide)", "neutral", 1,
     ["cream", "single cream", "double cream", "creme liquide"]),

    # ── CÉRÉALES COMPLÈTES ──────────────────────────────────────────────────
    ("oats", "whole_grain", "Oats", r"^(Flocon d'avoine|Avoine, flocon)", "neutral", 0,
     ["oats", "rolled oats", "porridge oats", "jumbo oats", "flocons d'avoine", "avoine"]),
    ("brown_rice", "whole_grain", "Brown rice", r"^Riz (brun|complet).*cru", "grain_absorbs", 0,
     ["brown rice", "wholegrain rice", "riz complet", "riz brun"]),
    ("quinoa", "whole_grain", "Quinoa", r"^Quinoa.*cru", "grain_absorbs", 0,
     ["quinoa"]),
    ("bulgur", "whole_grain", "Bulgur", r"^Boulg(ou|)r.*cru", "grain_absorbs", 0,
     ["bulgur", "bulghur", "boulgour"]),
    ("wholemeal_bread", "whole_grain", "Wholemeal bread", r"^Pain.*complet", "neutral", 0,
     ["wholemeal bread", "wholegrain bread", "brown bread", "pain complet", "wholemeal toast", "wholemeal wrap", "wholegrain wrap"]),
    ("wholewheat_pasta", "whole_grain", "Wholewheat pasta", r"^P(a|â)tes.*compl", "grain_absorbs", 0,
     ["wholewheat pasta", "wholemeal pasta", "pates completes"]),
    ("buckwheat", "whole_grain", "Buckwheat", r"^Sarrasin.*cru", "grain_absorbs", 0,
     ["buckwheat", "sarrasin", "blé noir"]),
    ("barley", "whole_grain", "Barley", r"^Orge.*cru", "grain_absorbs", 0,
     ["barley", "pearl barley", "orge"]),
    ("rye_bread", "whole_grain", "Rye bread", r"^Pain de seigle", "neutral", 0,
     ["rye bread", "pain de seigle"]),

    # ── CÉRÉALES RAFFINÉES ──────────────────────────────────────────────────
    ("white_rice", "refined_grain", "White rice", r"^Riz blanc.*cru", "grain_absorbs", 0,
     ["white rice", "rice", "basmati rice", "long grain rice", "jasmine rice", "riz", "riz blanc", "riz basmati"]),
    ("cooked_rice", "refined_grain", "Cooked rice", r"^Riz blanc.*cuit", "neutral", 0,
     ["cooked rice", "riz cuit", "leftover rice"]),
    ("white_pasta", "refined_grain", "Pasta", r"^P(a|â)tes s(e|è)ches standard, crues", "grain_absorbs", 0,
     ["pasta", "spaghetti", "penne", "fusilli", "tagliatelle", "macaroni", "pates"]),
    ("couscous", "refined_grain", "Couscous", r"^Semoule de bl(e|é) dur, crue", "grain_absorbs", 0,
     ["couscous", "semoule", "semoule de ble"]),
    ("white_bread", "refined_grain", "White bread", r"^Pain (de mie|blanc|baguette)", "neutral", 0,
     ["white bread", "bread", "baguette", "toast", "pain", "pain de mie", "wrap", "tortilla", "pitta", "pita bread"]),
    ("noodles", "refined_grain", "Noodles", r"^Nouille", "grain_absorbs", 0,
     ["noodles", "rice noodles", "udon", "nouilles"]),
    ("polenta", "refined_grain", "Polenta", r"^Polenta ou semoule", "grain_absorbs", 0,
     ["polenta"]),
    ("breakfast_cereal", "refined_grain", "Breakfast cereal", r"^C(e|é)r(e|é)ales pour petit d(e|é)jeuner \(aliment moyen\)", "neutral", 0,
     ["cornflakes", "breakfast cereal", "cereales"]),
    ("granola", "refined_grain", "Granola", r"^Muesli \(aliment moyen\)", "neutral", 1,
     ["granola", "muesli", "crunchy oat cereal"]),

    # ── LÉGUMES FÉCULENTS ───────────────────────────────────────────────────
    ("potato", "starchy_veg", "Potato", r"^Pomme de terre.*cru", "veg_shrinks", 0,
     ["potato", "potatoes", "new potatoes", "baby potatoes", "large potato", "pomme de terre", "pommes de terre"]),
    ("sweet_potato", "starchy_veg", "Sweet potato", r"^Patate douce.*cru", "veg_shrinks", 0,
     ["sweet potato", "sweet potatoes", "patate douce"]),
    ("butternut_squash", "starchy_veg", "Butternut squash", r"^(Courge butternut|Potiron).*cru", "veg_shrinks", 0,
     ["butternut squash", "squash", "pumpkin", "courge butternut", "potiron"]),
    ("sweetcorn", "starchy_veg", "Sweetcorn", r"^Ma(i|ï)s doux, appertis", "neutral", 0,
     ["sweetcorn", "corn", "tinned sweetcorn", "mais doux"]),
    ("beetroot", "starchy_veg", "Beetroot", r"^Betterave rouge.*cuite", "neutral", 0,
     ["beetroot", "beets", "betterave"]),
    ("parsnip", "starchy_veg", "Parsnip", r"^Panais.*cru", "veg_shrinks", 0,
     ["parsnip", "parsnips", "panais"]),

    # ── CRUCIFÈRES ──────────────────────────────────────────────────────────
    ("broccoli", "cruciferous_veg", "Broccoli", r"^Brocoli.*cru", "veg_shrinks", 0,
     ["broccoli", "tenderstem broccoli", "brocoli", "brocolis"]),
    ("cauliflower", "cruciferous_veg", "Cauliflower", r"^Chou-fleur.*cru", "veg_shrinks", 0,
     ["cauliflower", "chou-fleur", "chou fleur"]),
    ("brussels_sprouts", "cruciferous_veg", "Brussels sprouts", r"^Chou de Bruxelles.*cru", "veg_shrinks", 0,
     ["brussels sprouts", "sprouts", "choux de bruxelles"]),
    ("cabbage", "cruciferous_veg", "Cabbage", r"^Chou (vert|blanc).*cru", "veg_shrinks", 0,
     ["cabbage", "white cabbage", "savoy cabbage", "chou", "chou vert"]),
    ("red_cabbage", "cruciferous_veg", "Red cabbage", r"^Chou rouge.*cru", "veg_shrinks", 0,
     ["red cabbage", "chou rouge"]),
    ("kale", "cruciferous_veg", "Kale", r"^Chou fris(e|é).*cru", "veg_shrinks", 0,
     ["kale", "chou frise", "chou kale"]),
    ("pak_choi", "cruciferous_veg", "Pak choi", r"^Chou chinois.*cru", "veg_shrinks", 0,
     ["pak choi", "bok choy", "chou chinois"]),
    ("radish", "cruciferous_veg", "Radish", r"^Radis.*cru", "neutral", 0,
     ["radish", "radishes", "radis"]),

    # ── FEUILLES ────────────────────────────────────────────────────────────
    ("spinach", "leafy_greens", "Spinach", r"^(E|É)pinard.*cru", "veg_shrinks", 0,
     ["spinach", "baby spinach", "epinard", "epinards", "pousses d'epinard"]),
    ("rocket", "leafy_greens", "Rocket", r"^Roquette.*cru", "neutral", 0,
     ["rocket", "arugula", "roquette"]),
    ("lettuce", "leafy_greens", "Lettuce", r"^Laitue.*cru", "neutral", 0,
     ["lettuce", "salad leaves", "mixed salad leaves", "mixed leaves", "gem lettuce", "romaine", "laitue", "salade", "salade verte", "mesclun"]),
    ("swiss_chard", "leafy_greens", "Swiss chard", r"^Bette ou blette, cru", "veg_shrinks", 0,
     ["swiss chard", "chard", "blette", "blettes"]),
    ("watercress", "leafy_greens", "Watercress", r"^Cresson.*cru", "neutral", 0,
     ["watercress", "cresson"]),

    # ── LÉGUMES NON FÉCULENTS ───────────────────────────────────────────────
    ("carrot", "non_starchy_veg", "Carrot", r"^Carotte.*cru", "veg_shrinks", 0,
     ["carrot", "carrots", "carotte", "carottes", "baby carrots"]),
    ("courgette", "non_starchy_veg", "Courgette", r"^Courgette.*cru", "veg_shrinks", 0,
     ["courgette", "courgettes", "zucchini"]),
    ("bell_pepper", "non_starchy_veg", "Bell pepper", r"^Poivron.*cru", "veg_shrinks", 0,
     ["bell pepper", "bell peppers", "peppers", "red pepper", "red peppers", "yellow pepper", "poivron", "poivrons"]),
    ("tomato", "non_starchy_veg", "Tomato", r"^Tomate.*cru", "neutral", 0,
     ["tomato", "tomatoes", "cherry tomatoes", "vine tomatoes", "plum tomatoes", "tomate", "tomates", "tomates cerises"]),
    ("tinned_tomatoes", "non_starchy_veg", "Tinned tomatoes", r"^Tomate, pel(e|é)e, appertis", "neutral", 0,
     ["tinned tomatoes", "chopped tomatoes", "canned tomatoes", "tomates concassees", "tomates pelees"]),
    ("passata", "non_starchy_veg", "Passata", r"^Tomate, pur(e|é)e, appertis", "neutral", 0,
     ["passata", "tomato passata", "coulis de tomate"]),
    ("tomato_puree", "non_starchy_veg", "Tomato purée", r"^Tomate, concentr(e|é), appertis", "neutral", 0,
     ["tomato puree", "tomato paste", "concentre de tomate"]),
    ("cucumber", "non_starchy_veg", "Cucumber", r"^Concombre.*cru", "neutral", 0,
     ["cucumber", "concombre"]),
    ("mushroom", "non_starchy_veg", "Mushrooms", r"^Champignon de Paris.*cru", "veg_shrinks", 0,
     ["mushroom", "mushrooms", "chestnut mushrooms", "button mushrooms", "champignon", "champignons"]),
    ("onion", "non_starchy_veg", "Onion", r"^Oignon.*cru", "veg_shrinks", 0,
     ["onion", "onions", "red onion", "white onion", "oignon", "oignons", "oignon rouge"]),
    ("spring_onion", "non_starchy_veg", "Spring onion", r"^Ciboule ou Ciboulette", "neutral", 0,
     ["spring onion", "spring onions", "scallions", "oignon nouveau", "cebette"]),
    ("leek", "non_starchy_veg", "Leek", r"^Poireau.*cru", "veg_shrinks", 0,
     ["leek", "leeks", "poireau", "poireaux"]),
    ("green_beans", "non_starchy_veg", "Green beans", r"^Haricot vert.*cru", "veg_shrinks", 0,
     ["green beans", "french beans", "fine beans", "haricots verts", "haricot vert"]),
    ("aubergine", "non_starchy_veg", "Aubergine", r"^Aubergine.*cru", "veg_shrinks", 0,
     ["aubergine", "eggplant"]),
    ("celery", "non_starchy_veg", "Celery", r"^C(e|é)leri branche.*cru", "neutral", 0,
     ["celery", "celeri", "celeri branche"]),
    ("asparagus", "non_starchy_veg", "Asparagus", r"^Asperge.*cru", "veg_shrinks", 0,
     ["asparagus", "asperge", "asperges"]),
    ("fennel", "non_starchy_veg", "Fennel", r"^Fenouil.*cru", "veg_shrinks", 0,
     ["fennel", "fenouil"]),
    ("garlic", "non_starchy_veg", "Garlic", r"^Ail.*cru", "neutral", 0,
     ["garlic", "garlic clove", "garlic cloves", "ail", "gousse d'ail", "gousses d'ail"]),
    ("ginger", "non_starchy_veg", "Ginger", r"^Gingembre.*(frais|cru)", "neutral", 0,
     ["ginger", "fresh ginger", "gingembre"]),
    ("chilli", "non_starchy_veg", "Chilli", r"^Piment.*cru", "neutral", 0,
     ["chilli", "chili", "red chilli", "chillies", "piment"]),
    ("peas_frozen", "non_starchy_veg", "Frozen mixed vegetables", r"^L(e|é)gumes.*surgel", "neutral", 0,
     ["mixed vegetables", "frozen vegetables", "stir-fry vegetables", "legumes surgeles"]),
    ("olives", "non_starchy_veg", "Olives", r"^Olive (verte|noire)", "neutral", 1,
     ["olives", "black olives", "green olives", "olive"]),
    ("avocado", "other_fruit", "Avocado", r"^Avocat.*(pulpe|cru)", "neutral", 1,
     ["avocado", "avocados", "avocat"]),

    # ── FRUITS ──────────────────────────────────────────────────────────────
    ("banana", "other_fruit", "Banana", r"^Banane.*cru", "neutral", 0,
     ["banana", "bananas", "banane", "bananes"]),
    ("apple", "other_fruit", "Apple", r"^Pomme.*(pulpe|cru)", "neutral", 0,
     ["apple", "apples", "pomme", "pommes"]),
    ("pear", "other_fruit", "Pear", r"^Poire.*cru", "neutral", 0,
     ["pear", "pears", "poire"]),
    ("kiwi", "other_fruit", "Kiwi", r"^Kiwi.*cru", "neutral", 0,
     ["kiwi", "kiwis"]),
    ("mango", "other_fruit", "Mango", r"^Mangue.*cru", "neutral", 0,
     ["mango", "mangue"]),
    ("grapes", "other_fruit", "Grapes", r"^Raisin.*cru", "neutral", 0,
     ["grapes", "raisin frais"]),
    ("peach", "other_fruit", "Peach", r"^P(e|ê)che.*cru", "neutral", 0,
     ["peach", "peaches", "nectarine", "peche", "peches"]),
    ("pineapple", "other_fruit", "Pineapple", r"^Ananas.*cru", "neutral", 0,
     ["pineapple", "ananas"]),
    ("melon", "other_fruit", "Melon", r"^Melon.*cru", "neutral", 0,
     ["melon", "cantaloupe", "watermelon", "pasteque"]),
    ("blueberries", "berries", "Blueberries", r"^(Myrtille|Bleuet).*cru", "neutral", 0,
     ["blueberries", "blueberry", "myrtilles"]),
    ("strawberries", "berries", "Strawberries", r"^Fraise.*cru", "neutral", 0,
     ["strawberries", "strawberry", "fraises"]),
    ("raspberries", "berries", "Raspberries", r"^Framboise.*cru", "neutral", 0,
     ["raspberries", "raspberry", "framboises"]),
    ("mixed_berries", "berries", "Mixed berries", r"^Fruits rouges, crus", "neutral", 0,
     ["berries", "mixed berries", "frozen berries", "fruits rouges", "summer fruits"]),
    ("orange", "citrus", "Orange", r"^Orange.*(pulpe|cru)", "neutral", 0,
     ["orange", "oranges"]),
    ("lemon", "citrus", "Lemon", r"^Citron.*(pulpe|cru)", "neutral", 0,
     ["lemon", "lemons", "lemon juice", "lemon zest", "citron", "jus de citron"]),
    ("lime", "citrus", "Lime", r"^Citron vert.*cru", "neutral", 0,
     ["lime", "limes", "lime juice", "citron vert"]),
    ("grapefruit", "citrus", "Grapefruit", r"^Pamplemousse.*cru", "neutral", 0,
     ["grapefruit", "pamplemousse"]),
    ("clementine", "citrus", "Clementine", r"^(Cl(e|é)mentine|Mandarine).*cru", "neutral", 0,
     ["clementine", "clementines", "satsuma", "mandarin", "clementine"]),
    ("dried_apricot", "other_fruit", "Dried apricots", r"^Abricot sec", "neutral", 1,
     ["dried apricots", "abricots secs"]),
    ("raisins", "other_fruit", "Raisins", r"^Raisin, sec", "neutral", 1,
     ["raisins", "sultanas", "raisins secs"]),
    ("dates", "other_fruit", "Dates", r"^Datte", "neutral", 1,
     ["dates", "medjool dates", "dattes"]),

    # ── FRUITS À COQUE ET GRAINES (classe DENSE) ────────────────────────────
    ("almonds", "nuts_seeds", "Almonds", r"^Amande", "neutral", 1,
     ["almonds", "almond", "flaked almonds", "ground almonds", "amandes"]),
    ("walnuts", "nuts_seeds", "Walnuts", r"^Noix,", "neutral", 1,
     ["walnuts", "walnut", "noix"]),
    ("cashews", "nuts_seeds", "Cashews", r"^Noix de cajou", "neutral", 1,
     ["cashews", "cashew nuts", "noix de cajou"]),
    ("hazelnuts", "nuts_seeds", "Hazelnuts", r"^Noisette", "neutral", 1,
     ["hazelnuts", "noisettes"]),
    ("peanuts", "nuts_seeds", "Peanuts", r"^Cacahu(e|è)te ou Arachide", "neutral", 1,
     ["peanuts", "peanut", "cacahuetes", "cacahuete"]),
    ("peanut_butter", "nuts_seeds", "Peanut butter", r"^Beurre de cacahu", "neutral", 1,
     ["peanut butter", "beurre de cacahuete"]),
    ("mixed_nuts", "nuts_seeds", "Mixed nuts", r"^Fruits (a|à) coque", "neutral", 1,
     ["mixed nuts", "nuts", "fruits a coque"]),
    ("chia_seeds", "nuts_seeds", "Chia seeds", r"^Chia, graine", "neutral", 1,
     ["chia seeds", "chia", "graines de chia"]),
    ("pumpkin_seeds", "nuts_seeds", "Pumpkin seeds", r"^(Courge, graine|Graine de courge)", "neutral", 1,
     ["pumpkin seeds", "graines de courge"]),
    ("sunflower_seeds", "nuts_seeds", "Sunflower seeds", r"^Tournesol, graine", "neutral", 1,
     ["sunflower seeds", "graines de tournesol"]),
    ("sesame_seeds", "nuts_seeds", "Sesame seeds", r"^S(e|é)same, graine", "neutral", 1,
     ["sesame seeds", "graines de sesame"]),
    ("tahini", "nuts_seeds", "Tahini", r"^Tahin", "neutral", 1,
     ["tahini", "tahin", "puree de sesame"]),
    ("flaxseed", "nuts_seeds", "Flaxseed", r"^Lin, graine", "neutral", 1,
     ["flaxseed", "linseed", "graines de lin"]),

    # ── MATIÈRES GRASSES (classe DENSE) ─────────────────────────────────────
    ("olive_oil", "olive_oil", "Olive oil", r"^Huile d'olive", "neutral", 1,
     ["olive oil", "extra virgin olive oil", "huile d'olive", "oil"]),
    ("rapeseed_oil", "other_added_fat", "Rapeseed oil", r"^Huile de colza", "neutral", 1,
     ["rapeseed oil", "canola oil", "vegetable oil", "huile de colza", "huile vegetale"]),
    ("sunflower_oil", "other_added_fat", "Sunflower oil", r"^Huile de tournesol", "neutral", 1,
     ["sunflower oil", "huile de tournesol"]),
    ("coconut_oil", "other_added_fat", "Coconut oil", r"^Huile de coco", "neutral", 1,
     ["coconut oil", "huile de coco"]),
    ("sesame_oil", "other_added_fat", "Sesame oil", r"^Huile de s(e|é)same", "neutral", 1,
     ["sesame oil", "toasted sesame oil", "huile de sesame"]),
    ("butter", "other_added_fat", "Butter", r"^Beurre (a|à) 82% MG, doux", "neutral", 1,
     ["butter", "unsalted butter", "beurre"]),
    ("ghee", "other_added_fat", "Ghee", r"^Huile de beurre ou Beurre concentr", "neutral", 1,
     ["ghee", "beurre clarifie"]),
    ("coconut_milk", "other_added_fat", "Coconut milk", r"^Lait de coco", "neutral", 1,
     ["coconut milk", "lait de coco"]),

    # ── SAUCES ET CONDIMENTS ────────────────────────────────────────────────
    ("mayonnaise", "sauce_dressing", "Mayonnaise", r"^Mayonnaise", "neutral", 1,
     ["mayonnaise", "mayo", "light mayonnaise"]),
    ("ketchup", "sauce_dressing", "Ketchup", r"^Ketchup", "neutral", 0,
     ["ketchup"]),
    ("soy_sauce", "sauce_dressing", "Soy sauce", r"^Sauce soja", "neutral", 0,
     ["soy sauce", "soya sauce", "tamari", "sauce soja"]),
    ("mustard", "sauce_dressing", "Mustard", r"^Moutarde", "neutral", 0,
     ["mustard", "dijon mustard", "wholegrain mustard", "moutarde"]),
    ("vinaigrette", "sauce_dressing", "Vinaigrette", r"^Sauce vinaigrette \(50", "neutral", 1,
     ["vinaigrette", "salad dressing", "french dressing"]),
    ("pesto", "sauce_dressing", "Pesto", r"^Sauce pesto, pr(e|é)emball", "neutral", 1,
     ["pesto"]),
    ("vinegar", "sauce_dressing", "Vinegar", r"^Vinaigre", "neutral", 0,
     ["vinegar", "balsamic vinegar", "cider vinegar", "vinaigre", "vinaigre balsamique"]),
    ("salsa", "sauce_dressing", "Salsa", r"^Sauce.*tomate.*(m(e|é)xicaine|piquante)", "neutral", 0,
     ["salsa", "tomato salsa"]),
    ("curry_paste", "sauce_dressing", "Curry paste", r"^(Curry|P(a|â)te de curry)", "neutral", 0,
     ["curry paste", "curry powder", "pate de curry", "curry"]),
    ("stock_cube", "sauce_dressing", "Stock", r"^Bouillon", "neutral", 0,
     ["stock", "chicken stock", "vegetable stock", "beef stock", "stock cube", "bouillon", "broth"]),
    ("salt", "sauce_dressing", "Salt", r"^Sel (blanc|de cuisine)", "neutral", 0,
     ["salt", "sea salt", "sel", "salt and pepper"]),
    ("black_pepper", "sauce_dressing", "Black pepper", r"^Poivre noir", "neutral", 0,
     ["black pepper", "poivre", "poivre noir"]),
    ("paprika", "sauce_dressing", "Paprika", r"^Paprika", "neutral", 0,
     ["paprika", "smoked paprika"]),
    ("cumin", "sauce_dressing", "Cumin", r"^Cumin", "neutral", 0,
     ["cumin", "ground cumin"]),
    ("cinnamon", "sauce_dressing", "Cinnamon", r"^Cannelle", "neutral", 0,
     ["cinnamon", "cannelle"]),
    ("chilli_powder", "sauce_dressing", "Chilli powder", r"^Piment.*(poudre|moulu)", "neutral", 0,
     ["chilli powder", "chili powder", "chilli flakes", "piment en poudre"]),
    ("herbs_parsley", "leafy_greens", "Parsley", r"^Persil.*(frais|cru)", "neutral", 0,
     ["parsley", "flat-leaf parsley", "persil"]),
    ("herbs_coriander", "leafy_greens", "Coriander", r"^Coriandre.*(fra(i|î)che|feuille)", "neutral", 0,
     ["coriander", "cilantro", "coriandre"]),
    ("herbs_basil", "leafy_greens", "Basil", r"^Basilic.*(frais|cru)", "neutral", 0,
     ["basil", "basilic"]),
    ("herbs_mint", "leafy_greens", "Mint", r"^Menthe.*(fra(i|î)che|cru)", "neutral", 0,
     ["mint", "menthe"]),
    ("herbs_thyme", "leafy_greens", "Thyme", r"^Thym", "neutral", 0,
     ["thyme", "thym", "rosemary", "romarin"]),

    # ── SUCRES ET DOUCEURS (classe DENSE) ───────────────────────────────────
    ("honey", "sugar_sweets", "Honey", r"^Miel", "neutral", 1,
     ["honey", "miel"]),
    ("maple_syrup", "sugar_sweets", "Maple syrup", r"^Sirop d'(e|é)rable", "neutral", 1,
     ["maple syrup", "sirop d'erable"]),
    ("sugar", "sugar_sweets", "Sugar", r"^Sucre blanc", "neutral", 1,
     ["sugar", "caster sugar", "brown sugar", "sucre"]),
    ("dark_chocolate", "sugar_sweets", "Dark chocolate", r"^Chocolat noir", "neutral", 1,
     ["dark chocolate", "chocolat noir"]),
    ("jam", "sugar_sweets", "Jam", r"^Confiture", "neutral", 1,
     ["jam", "confiture"]),
    ("biscuits", "sugar_sweets", "Biscuits", r"^Biscuit sec", "neutral", 1,
     ["biscuits", "biscuit", "cookies", "biscuits secs"]),
    ("ice_cream", "sugar_sweets", "Ice cream", r"^(Cr(e|è)me glac(e|é)e|Glace)", "neutral", 1,
     ["ice cream", "glace", "creme glacee"]),

    # ── FRIT ────────────────────────────────────────────────────────────────
    ("chips_fries", "fried_food", "Chips / fries", r"^Frites de pommes de terre, surgel(e|é)es, r(o|ô)ties", "neutral", 1,
     ["chips", "fries", "french fries", "frites"]),
    ("crisps", "fried_food", "Crisps", r"^Chips de pommes de terre nature ou aromatis(e|é)es, standard", "neutral", 1,
     ["crisps", "potato chips"]),

    # ── BOISSONS ────────────────────────────────────────────────────────────
    ("water", "water", "Water", r"^Eau (du robinet|de distribution)", "neutral", 0,
     ["water", "eau", "cold water", "boiling water"]),
    ("coffee", "coffee_tea", "Coffee", r"^Caf(e|é), non instantan", "neutral", 0,
     ["coffee", "black coffee", "cafe"]),
    ("tea", "coffee_tea", "Tea", r"^Th(e|é) infus(e|é), non sucr", "neutral", 0,
     ["tea", "black tea", "green tea", "the", "the vert"]),
    ("beer", "alcohol", "Beer", r"^Bi(e|è)re", "neutral", 0,
     ["beer", "biere"]),
    ("wine", "alcohol", "Wine", r"^Vin (rouge|blanc)", "neutral", 0,
     ["wine", "red wine", "white wine", "vin"]),
    ("orange_juice", "sweetened_beverage", "Orange juice", r"^Jus d'orange", "neutral", 0,
     ["orange juice", "fruit juice", "jus d'orange", "jus de fruit"]),
    ("cola", "sweetened_beverage", "Cola", r"^(Cola|Boisson.*cola)", "neutral", 0,
     ["cola", "soft drink"]),
]

# ── LES ALIMENTS QUE CIQUAL 2020 NE PORTE PAS ────────────────────────────────
# Un référentiel n'est pas moins honnête parce qu'il a deux sources; il l'est
# quand il ne dit pas laquelle. Ces valeurs sont écrites à la main (tables de
# composition usuelles, pour 100 g), et la ligne en base porte `source =
# 'manual'` — un lecteur qui veut savoir ce qui vient de l'ANSES peut le lire.
#
# kcal, protein, carbs, fat, fiber, puis les drapeaux VRAIS (les autres sont
# faux). Aucune de ces entrées n'invente une sentinelle: un drapeau n'est posé
# que sur un fait de composition connu et grossier (le lait est source de
# calcium, les graines de courge de zinc et de fer).
MANUAL = {
    "black_beans":     (132, 8.9, 23.7, 0.5, 8.7, ["iron_source", "folate_source"]),
    "baked_beans":     (94, 4.8, 15.0, 0.6, 4.9, ["iron_source"]),
    "edamame":         (121, 12.0, 8.9, 5.2, 5.2, ["iron_source", "folate_source"]),
    "hummus":          (237, 7.4, 14.0, 17.1, 6.0, ["iron_source"]),
    "greek_yogurt":    (97, 9.0, 3.6, 5.0, 0.0, ["calcium_source", "b12_source"]),
    "plain_yogurt":    (59, 3.5, 4.7, 3.3, 0.0, ["calcium_source", "b12_source"]),
    "skyr":            (63, 11.0, 4.0, 0.2, 0.0, ["calcium_source", "b12_source"]),
    "cottage_cheese":  (98, 11.1, 3.4, 4.3, 0.0, ["b12_source"]),
    "kefir":           (55, 3.3, 4.5, 2.5, 0.0, ["calcium_source", "b12_source"]),
    "milk_semi":       (46, 3.3, 4.8, 1.6, 0.0, ["calcium_source", "b12_source"]),
    "halloumi":        (321, 22.0, 2.2, 25.0, 0.0, ["calcium_source", "b12_source"]),
    "cream_cheese":    (253, 6.0, 4.0, 24.0, 0.0, []),
    "creme_fraiche":   (292, 2.4, 2.9, 30.0, 0.0, []),
    "single_cream":    (198, 2.6, 3.3, 19.0, 0.0, []),
    "wholewheat_pasta": (348, 13.0, 62.0, 2.5, 8.0, ["iron_source", "zinc_source"]),
    "coconut_oil":     (890, 0.0, 0.0, 99.0, 0.0, []),
    "pumpkin_seeds":   (559, 30.2, 10.7, 49.0, 6.0, ["iron_source", "zinc_source", "folate_source"]),
    "mixed_nuts":      (607, 18.0, 13.0, 53.0, 7.5, ["iron_source", "zinc_source"]),
    "dried_apricot":   (241, 3.4, 53.0, 0.5, 7.3, ["iron_source"]),
    "salsa":           (36, 1.3, 6.6, 0.2, 1.5, []),
    "chilli_powder":   (282, 12.0, 30.0, 14.0, 28.0, ["iron_source"]),
    "salt":            (0, 0.0, 0.0, 0.0, 0.0, []),
    "black_pepper":    (251, 10.4, 39.0, 3.3, 25.0, ["iron_source"]),
    "water":           (0, 0.0, 0.0, 0.0, 0.0, []),
    "broad_beans":     (110, 7.6, 11.7, 0.4, 5.4, ["iron_source", "folate_source"]),
    "stock_cube":      (5, 0.4, 0.6, 0.1, 0.0, []),
}
