import { assertEquals } from "jsr:@std/assert@1";

import { buildCoachingInterventionTraceScorecard } from "./coaching_intervention_scorecard.ts";

Deno.test("buildCoachingInterventionTraceScorecard aggregates coaching outcomes", () => {
  const scorecard = buildCoachingInterventionTraceScorecard({
    trace: {
      user_id: "00000000-0000-0000-0000-000000000001",
      window: {
        from: "2026-03-19T00:00:00.000Z",
        to: "2026-03-20T00:00:00.000Z",
        scope: "whatsapp",
      },
      summary: {
        messages_total: 2,
        user_messages: 1,
        assistant_messages: 1,
        turns_total: 1,
        selector_runs_total: 2,
        interventions_total: 2,
        follow_ups_total: 2,
        weekly_surfaces_total: 1,
        observability_events_total: 7,
      },
      messages: [],
      turns: [{
        turn_id: "msg-user-1",
        request_id: "req-1",
        started_at: "2026-03-19T10:00:00.000Z",
        scope: "whatsapp",
        channel: "whatsapp",
        user_message: null,
        assistant_messages: [],
        selector_runs: [{
          id: 20,
          at: "2026-03-19T10:00:01.000Z",
          event_name: "coaching_technique_deprioritized",
          source_component: "coaching_selector",
          request_id: "req-1",
          turn_id: "msg-user-1",
          payload: {},
        }],
        intervention_events: [],
        follow_up_events: [],
        events: [],
      }],
      selector_runs: [
        {
          id: 1,
          at: "2026-03-19T10:00:01.000Z",
          request_id: "req-1",
          turn_id: "msg-user-1",
          source_component: "coaching_selector",
          trigger_type: "explicit_blocker",
          momentum_state: "friction_legere",
          blocker_type: "startup_inertia",
          confidence: "low",
          eligible: true,
          skip_reason: null,
          recommended_technique: "minimum_version",
          candidate_techniques: ["minimum_version"],
          follow_up_needed: true,
          customization_context: null,
          payload: { gate: "allow" },
        },
        {
          id: 2,
          at: "2026-03-19T11:00:01.000Z",
          request_id: "req-2",
          turn_id: "msg-user-2",
          source_component: "coaching_selector",
          trigger_type: "explicit_craving",
          momentum_state: "friction_legere",
          blocker_type: "craving_or_urge",
          confidence: "medium",
          eligible: false,
          skip_reason: "blocked",
          recommended_technique: null,
          candidate_techniques: [],
          follow_up_needed: false,
          customization_context: null,
          payload: { gate: "blocked" },
        },
      ],
      interventions: [
        {
          intervention_id: "coach_1",
          proposed_at: "2026-03-19T10:00:03.000Z",
          request_id: "req-1",
          turn_id: "msg-user-1",
          source_component: "router",
          trigger_type: "explicit_blocker",
          momentum_state: "friction_legere",
          blocker_type: "startup_inertia",
          confidence: "low",
          recommended_technique: "minimum_version",
          candidate_techniques: ["minimum_version"],
          follow_up_needed: true,
          follow_up_due_at: null,
          customization_context: null,
          proposal: {
            id: 3,
            at: "2026-03-19T10:00:03.000Z",
            event_name: "coaching_intervention_proposed",
            source_component: "router",
            request_id: "req-1",
            turn_id: "msg-user-1",
            payload: {},
          },
          render: null,
          follow_up: {
            id: 4,
            at: "2026-03-19T18:00:00.000Z",
            event_name: "coaching_followup_classified",
            source_component: "router",
            request_id: "req-2",
            turn_id: "msg-user-2",
            payload: { follow_up_outcome: "behavior_changed" },
          },
          events: [],
        },
        {
          intervention_id: "coach_2",
          proposed_at: "2026-03-19T12:00:03.000Z",
          request_id: "req-3",
          turn_id: "msg-user-3",
          source_component: "router",
          trigger_type: "explicit_craving",
          momentum_state: "friction_legere",
          blocker_type: "craving_or_urge",
          confidence: "medium",
          recommended_technique: "urge_delay",
          candidate_techniques: ["urge_delay"],
          follow_up_needed: true,
          follow_up_due_at: null,
          customization_context: null,
          proposal: {
            id: 5,
            at: "2026-03-19T12:00:03.000Z",
            event_name: "coaching_intervention_proposed",
            source_component: "router",
            request_id: "req-3",
            turn_id: "msg-user-3",
            payload: {},
          },
          render: null,
          follow_up: {
            id: 6,
            at: "2026-03-19T20:00:00.000Z",
            event_name: "coaching_followup_classified",
            source_component: "router",
            request_id: "req-4",
            turn_id: "msg-user-4",
            payload: { follow_up_outcome: "tried_not_helpful" },
          },
          events: [],
        },
      ],
      follow_ups: [
        {
          id: 4,
          at: "2026-03-19T18:00:00.000Z",
          request_id: "req-2",
          turn_id: "msg-user-2",
          source_component: "router",
          intervention_id: "coach_1",
          blocker_type: "startup_inertia",
          recommended_technique: "minimum_version",
          follow_up_outcome: "behavior_changed",
          helpful: true,
          payload: {},
        },
        {
          id: 6,
          at: "2026-03-19T20:00:00.000Z",
          request_id: "req-4",
          turn_id: "msg-user-4",
          source_component: "router",
          intervention_id: "coach_2",
          blocker_type: "craving_or_urge",
          recommended_technique: "urge_delay",
          follow_up_outcome: "tried_not_helpful",
          helpful: false,
          payload: {},
        },
      ],
      weekly_surfaces: [{
        id: 7,
        at: "2026-03-19T21:00:00.000Z",
        request_id: "weekly-1",
        source_component: "trigger_weekly_bilan",
        weekly_recommendation: "switch_technique",
        summary: "Changer d'approche.",
        payload: {},
      }],
      unassigned_events: [],
    },
    annotations: [],
  });

  assertEquals(scorecard.gating.eligible_total, 1);
  assertEquals(scorecard.gating.blocked_total, 1);
  assertEquals(scorecard.techniques.proposed_by_technique.minimum_version, 1);
  assertEquals(scorecard.techniques.not_helpful_by_technique.urge_delay, 1);
  assertEquals(scorecard.effectiveness.behavior_changed_total, 1);
  assertEquals(scorecard.alerts.low_confidence_selector_runs, 1);
  assertEquals(scorecard.weekly.recommendation_distribution.switch_technique, 1);
});
